[package]
name = "yfoil"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.127"
serde = { version = "1.0.209", features = ["derive"] }
plotly = "0.9.0"
clap = { version = "4.5.16", features = ["derive"] }
