//! The validity record (`yfoil::solver::validity`) and the result record built from it.
//!
//! The classification is checked against XFOIL itself, not against yFoil's own output: the
//! instrumented reference logs every occasion the record describes as an event in
//! `events.dat` (`xfoil/instrumentation/instrument/19-validity-events.patch`), and XFOIL is
//! otherwise silent about most of them. Each SPECAL call opens a span with a `SPECAL_ENTER`
//! marker, so the events of one operating point are the lines between its marker and the next.
//!
//! The comparison respects a difference in granularity that is by design: an event fires on
//! *any* call within the span — including the intermediate iterates of SPECAL's CL(M) Newton —
//! while yFoil's record describes the *reported* state, the last call. So:
//!
//! - where XFOIL's record is per point (SPECAL's CL(M) Newton exhausted, logged once after the
//!   loop), yFoil's flag must equal the event exactly;
//! - where it is per call (MRCL's substitutions, CLCALC's and CPCALC's Kármán–Tsien test), a
//!   yFoil flag must have its event in the span — the reported state cannot have taken a branch
//!   XFOIL never took — while an event may appear without the flag when only an intermediate
//!   iterate took it.
//!
//! Cases (`xtask/fixtures-config/cases.toml`, regenerated by `cargo xtask fixtures --case <name>`):
//! `naca4412_n60_inviscid_m07_a10` (a fixed-Mach point past the Kármán–Tsien pole) and
//! `naca64a010_n60_inviscid_sweep30_type2_m03` (the TYPE 2 sweep of known issues §7.7). The
//! viscous iteration exhaustion is checked on the reference case, whose recorded RMSBL at an
//! iteration cap of 3 is far above XFOIL's tolerance.

mod fixtures;

use std::path::Path;
use yfoil::bl::system::{MachClDependence, ReClDependence};
use yfoil::geometry::{panel_foil, read_geometry_from_file};
use yfoil::output::{PointRecord, PointStatus, Reason};
use yfoil::solver::analysis::{FlowConditions, Session};
use yfoil::solver::validity::ValidityRecord;

#[test]
fn test_default_record_asserts_nothing() {
    let v = ValidityRecord::default();
    assert!(
        v.karman_tsien_margin_forces.is_infinite() && v.karman_tsien_margin_pressure.is_infinite(),
        "an unevaluated margin must not read as a violation"
    );
    assert!(!v.out_of_domain());
    assert!(!v.iteration_exhausted());
    assert!(!v.conditions_substituted());
}

#[test]
fn test_incompressible_margin_is_one() {
    // at M = 0, beta = 1 and bfac = 0, so the denominator is 1 at every node whatever the speed:
    // the Kármán–Tsien correction cannot be out of domain in incompressible flow
    let q: Vec<f64> = (0..=40).map(|i| i as f64 * 0.5).collect();
    let (_, margin) = yfoil::solver::clcalc::compute_cp(40, &q, 1.0, 0.0);
    assert_eq!(margin, 1.0);
}

fn case_dir(case: &str) -> std::path::PathBuf {
    fixtures::require_fixture(&format!("tests/fixtures/xfoil/{case}"))
}

/// The events of one SPECAL call: the sites logged between its `SPECAL_ENTER` and the next.
#[derive(Debug, Default)]
struct Span {
    alpha_deg: f64,
    sites: Vec<String>,
}

impl Span {
    fn has(&self, site: &str) -> bool {
        self.sites.iter().any(|s| s == site)
    }
}

fn spans(dir: &Path) -> Vec<Span> {
    let text = std::fs::read_to_string(dir.join("events.dat")).expect("events.dat");
    let mut out: Vec<Span> = vec![];
    for line in text.lines() {
        let t: Vec<&str> = line.split_whitespace().collect();
        assert!(t.len() == 6 && t[0] == "EV", "malformed event line: {line}");
        if t[1] == "SPECAL_ENTER" {
            let alfa: f64 = t[5].parse().unwrap();
            out.push(Span {
                alpha_deg: alfa.to_degrees(),
                sites: vec![],
            });
        } else {
            out.last_mut()
                .expect("an event before the first SPECAL_ENTER")
                .sites
                .push(t[1].to_string());
        }
    }
    out
}

/// Run the case's ALFA sequence inviscid through one session, as the reference did, and pair
/// each point's validity record with XFOIL's span of events.
fn run_inviscid(case: &str, mach: f64, type2: bool) -> Vec<(Span, ValidityRecord)> {
    let dir = case_dir(case);
    let geometry = read_geometry_from_file(dir.join("panels.json").to_str().unwrap()).unwrap();
    let mut session = Session::new(
        &panel_foil(&geometry),
        FlowConditions {
            re: None,
            mach,
            mach_cl_dependence: if type2 {
                MachClDependence::InverseSqrtCl
            } else {
                MachClDependence::Fixed
            },
            re_cl_dependence: if type2 {
                ReClDependence::InverseSqrtCl
            } else {
                ReClDependence::Fixed
            },
            ..FlowConditions::default()
        },
    );
    spans(&dir)
        .into_iter()
        .map(|span| {
            let p = session.alpha(span.alpha_deg.to_radians());
            (span, p.validity)
        })
        .collect()
}

/// The per-call flags: a flag on the reported state needs its event in XFOIL's span.
fn assert_flags_have_events(points: &[(Span, ValidityRecord)]) {
    for (span, v) in points {
        let a = span.alpha_deg;
        let pairs = [
            (v.karman_tsien_margin_forces <= 0.0, "CLCALC_KT_DOMAIN"),
            (v.karman_tsien_margin_pressure <= 0.0, "CPCALC_KT_DOMAIN"),
            (v.cl_floored, "MRCL_CL_FLOOR"),
            (v.mach_limited, "MRCL_MACH_LIMIT"),
            (v.re_limited, "MRCL_RE_LIMIT"),
        ];
        for (flag, site) in pairs {
            assert!(
                !flag || span.has(site),
                "alpha {a}: yFoil's reported state took the {site} branch, XFOIL's span never did"
            );
        }
    }
}

#[test]
fn test_point_past_the_karman_tsien_pole_matches_xfoil() {
    let points = run_inviscid("naca4412_n60_inviscid_m07_a10", 0.7, false);
    assert_eq!(points.len(), 1);
    let (span, v) = &points[0];
    // at a fixed Mach every call of the span sees the same denominator, so here the event and
    // the flag must agree in both directions
    assert!(
        span.has("CLCALC_KT_DOMAIN") && span.has("CPCALC_KT_DOMAIN"),
        "the reference crossed the pole"
    );
    assert!(
        v.karman_tsien_margin_forces <= 0.0 && v.karman_tsien_margin_pressure <= 0.0,
        "yFoil must record the crossing XFOIL logged: {v:?}"
    );
    assert!(v.out_of_domain() && !v.iteration_exhausted() && !v.conditions_substituted());
}

#[test]
fn test_type2_sweep_mach_newton_exhaustion_matches_xfoil_exactly() {
    let points = run_inviscid("naca64a010_n60_inviscid_sweep30_type2_m03", 0.3, true);
    assert_eq!(points.len(), 61, "one SPECAL per degree from -30 to 30");
    let ours: Vec<i64> = points
        .iter()
        .filter(|(_, v)| v.mach_cl_newton_exhausted)
        .map(|(s, _)| s.alpha_deg.round() as i64)
        .collect();
    let xfoil: Vec<i64> = points
        .iter()
        .filter(|(s, _)| s.has("SPECAL_MINF_FAIL"))
        .map(|(s, _)| s.alpha_deg.round() as i64)
        .collect();
    assert!(!xfoil.is_empty(), "the sweep must exercise the exhaustion");
    assert_eq!(ours, xfoil, "SPECAL's CL(M) Newton exhausted at exactly XFOIL's points");
}

#[test]
fn test_type2_sweep_flags_are_taken_only_where_xfoil_took_them() {
    let points = run_inviscid("naca64a010_n60_inviscid_sweep30_type2_m03", 0.3, true);
    assert_flags_have_events(&points);
    // and the sweep is not vacuous: every kind of flag is raised somewhere
    assert!(points.iter().any(|(_, v)| v.out_of_domain()));
    assert!(points.iter().any(|(_, v)| v.cl_floored && v.mach_limited));
}

#[test]
fn test_viscous_iteration_exhaustion_withholds_the_numbers() {
    // the reference case converges in 6 iterations; capped at 3 it cannot, and not marginally:
    // XFOIL's own RMSBL after iteration 3 is recorded in viscal_iters_all.dat, far above EPS1
    let dir = fixtures::require_fixture(fixtures::REF_CASE);
    let iters = std::fs::read_to_string(dir.join("viscal_iters_all.dat")).unwrap();
    let rmsbl3: f64 = iters
        .lines()
        .find(|l| l.split_whitespace().take(3).collect::<Vec<_>>() == ["IT", "1", "3"])
        .and_then(|l| l.split_whitespace().nth(3))
        .unwrap()
        .parse()
        .unwrap();
    assert!(
        rmsbl3 > 100.0 * 1e-4,
        "RMSBL after 3 iterations is {rmsbl3}: not near EPS1"
    );

    let geometry = read_geometry_from_file(dir.join("panels.json").to_str().unwrap()).unwrap();
    let mut session = Session::new(
        &panel_foil(&geometry),
        FlowConditions {
            re: Some(1.0e6),
            max_iterations: 3,
            ..FlowConditions::default()
        },
    );
    let p = session.alpha(2.0_f64.to_radians());
    assert!(!p.converged);
    let r = PointRecord::from_point(&p, true, false);
    assert_eq!(r.status, PointStatus::Invalid);
    assert!(r.reasons.contains(&Reason::ViscousNotConverged), "{:?}", r.reasons);
    assert!(r.values.is_none(), "an invalid point's numbers are withheld");
    let r = PointRecord::from_point(&p, true, true);
    assert_eq!(
        r.status,
        PointStatus::Invalid,
        "--allow-invalid never changes the status"
    );
    assert!(r.values.is_some(), "--allow-invalid populates the numbers");
}

/// A polar is a state machine, not N independent solves: each point starts from the previous
/// point's boundary layer. The result is presented ascending in alpha, which is *not* the order
/// it was solved in, so every record carries a content-addressed `id` and `initialised_from`
/// citing the record that seeded it.
mod execution_chain {
    use super::case_dir;
    use yfoil::geometry::{panel_foil, read_geometry_from_file};
    use yfoil::output::{PointStatus, PolarOutput};
    use yfoil::solver::analysis::{compute_polar, FlowConditions, PolarConfig};

    fn polar() -> PolarOutput {
        let dir = case_dir("naca0012_n60_polar_re1e6");
        let geometry = read_geometry_from_file(dir.join("panels.json").to_str().unwrap()).unwrap();
        let airfoil = panel_foil(&geometry);
        let result = compute_polar(
            &airfoil,
            &PolarConfig {
                alpha_max: 4.0,
                alpha_min: -4.0,
                alpha_step: 1.0,
                conditions: FlowConditions {
                    re: Some(1.0e6),
                    ncrit: 9.0,
                    max_iterations: 20,
                    ..FlowConditions::default()
                },
                ..PolarConfig::default()
            },
        );
        PolarOutput::from_polar(&result, "naca0012", false)
    }

    #[test]
    fn test_records_are_presented_ascending_in_alpha() {
        let p = polar();
        assert!(
            p.results.windows(2).all(|w| w[0].alpha_deg < w[1].alpha_deg),
            "results are ordered by alpha, not by when they were solved"
        );
    }

    #[test]
    fn test_execution_order_is_recoverable_by_following_the_chain() {
        let p = polar();
        // walk each leg from its root: the chain is the only record of what ran when, since the
        // presentation is ascending in alpha and the ids carry no order of their own
        let next_after = |id: &str| p.results.iter().find(|r| r.initialised_from.as_deref() == Some(id));
        let root = p.results.iter().find(|r| r.initialised_from.is_none()).unwrap();
        assert!(root.alpha_deg.abs() < 1e-9, "the chain roots at the 0° solve");

        // two legs leave the root, so collect both and check they are the sweep XFOIL runs
        let legs: Vec<Vec<f64>> = p
            .results
            .iter()
            .filter(|r| r.initialised_from.as_deref() == root.id.as_deref())
            .map(|first| {
                let mut leg = vec![(first.alpha_deg * 2.0).round() / 2.0];
                let mut node = first;
                while let Some(n) = next_after(node.id.as_deref().unwrap()) {
                    leg.push((n.alpha_deg * 2.0).round() / 2.0);
                    node = n;
                }
                leg
            })
            .collect();
        assert_eq!(legs.len(), 2, "0° → max and 0° → min");
        let mut sorted = legs.clone();
        sorted.sort_by(|a, b| a[0].partial_cmp(&b[0]).unwrap());
        assert_eq!(sorted[0], vec![-1.0, -2.0, -3.0, -4.0]);
        assert_eq!(sorted[1], vec![1.0, 2.0, 3.0, 4.0]);
    }

    #[test]
    fn test_ids_are_unique_and_well_formed() {
        let p = polar();
        let ids: Vec<&str> = p.results.iter().filter_map(|r| r.id.as_deref()).collect();
        assert!(ids.iter().all(|i| i.len() == yfoil::solver::point_id::ID_LENGTH
            && i.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit())));
        let mut unique: Vec<&str> = ids.clone();
        unique.sort_unstable();
        unique.dedup();
        assert_eq!(unique.len(), ids.len(), "ids collide");
    }

    #[test]
    fn test_ids_are_deterministic() {
        // content-addressed, so the same run gives the same ids and a result file is
        // byte-reproducible
        let (a, b) = (polar(), polar());
        let ids = |p: &PolarOutput| -> Vec<Option<String>> { p.results.iter().map(|r| r.id.clone()).collect() };
        assert_eq!(ids(&a), ids(&b));
    }

    #[test]
    fn test_the_id_covers_the_inputs_the_solve_depended_on() {
        let base = polar();
        let at = |p: &PolarOutput, a: f64| {
            p.results
                .iter()
                .find(|r| (r.alpha_deg - a).abs() < 1e-9)
                .unwrap()
                .id
                .clone()
        };
        // a different Reynolds number is a different computation at the same alpha
        let dir = case_dir("naca0012_n60_polar_re1e6");
        let geometry = read_geometry_from_file(dir.join("panels.json").to_str().unwrap()).unwrap();
        let airfoil = panel_foil(&geometry);
        let other = PolarOutput::from_polar(
            &compute_polar(
                &airfoil,
                &PolarConfig {
                    alpha_max: 4.0,
                    alpha_min: -4.0,
                    alpha_step: 1.0,
                    conditions: FlowConditions {
                        re: Some(3.0e6),
                        ncrit: 9.0,
                        max_iterations: 20,
                        ..FlowConditions::default()
                    },
                    ..PolarConfig::default()
                },
            ),
            "naca0012",
            false,
        );
        assert_ne!(at(&base, 0.0), at(&other, 0.0), "Re is part of the identity");
        assert_ne!(at(&base, 2.0), at(&other, 2.0));
    }

    #[test]
    fn test_the_predecessor_is_part_of_the_identity() {
        // 0° is solved twice in a sweep — once to open it, once after INIT to seed the downward
        // leg — and those two solves have identical inputs and no predecessor, so they are the
        // same computation and take the same id. That is what lets the downward leg cite the
        // recorded 0° point instead of a phantom: both legs cite one root (asserted in
        // `test_execution_order_is_recoverable_by_following_the_chain`).
        let p = polar();
        let at = |a: f64| p.results.iter().find(|r| (r.alpha_deg - a).abs() < 1e-9).unwrap();
        // +1 and -1 share a predecessor but differ in operating point, so differ in id
        assert_eq!(at(1.0).initialised_from, at(-1.0).initialised_from);
        assert_ne!(at(1.0).id, at(-1.0).id);
    }

    #[test]
    fn test_every_reference_resolves() {
        let p = polar();
        for r in &p.results {
            if let Some(from) = r.initialised_from.as_deref() {
                assert!(
                    p.results.iter().any(|q| q.id.as_deref() == Some(from)),
                    "alpha {} cites id {from}, which is not in the result",
                    r.alpha_deg
                );
            }
            if r.status == PointStatus::NotAttempted {
                assert!(
                    r.id.is_none() && r.initialised_from.is_none(),
                    "a point that was never solved has no place in the execution chain"
                );
            }
        }
    }
}
