//! The run's index (`README.md`, `README.tex`, `summary.json`) and the generated documentation
//! page (`docs/validation/aerofoil-series/README.md` with the figures).

use crate::naca456::CaseComparison;
use crate::study::{validation_set, SeriesStudy, N_NODES};
use std::fs;
use std::io::Write;
use std::path::Path;

fn te_gap(g: &yfoil::geometry::Geometry) -> f64 {
    let n = g.x.len();
    (g.x[0] - g.x[n - 1]).hypot(g.y[0] - g.y[n - 1])
}

fn max_thickness(g: &yfoil::geometry::Geometry) -> f64 {
    // the largest vertical extent between the two surfaces at the sampled stations, which are
    // symmetric in x for a symmetric section and near enough for the table
    let n = g.x.len() / 2;
    (0..n)
        .map(|i| (g.y[i] - g.y[g.x.len() - 1 - i]).abs())
        .fold(0.0, f64::max)
}

pub fn write_summary_json(run_dir: &Path, series: &[&SeriesStudy], comparison: &[CaseComparison]) {
    let member = |m: &crate::study::Member| {
        serde_json::json!({
            "designation": m.designation, "label": m.label, "value": m.value, "file": format!("{}.json", m.slug),
            "n_nodes": m.geometry.x.len(), "te_gap": te_gap(&m.geometry), "max_thickness": max_thickness(&m.geometry),
            "generator": m.geometry.generator,
        })
    };
    let series_json: Vec<serde_json::Value> = series
        .iter()
        .map(|s| {
            serde_json::json!({
                "slug": s.slug, "title": s.title, "parameters": s.parameters, "references": s.references,
                "default": member(&s.default),
                "panels": s.panels.iter().map(|p| serde_json::json!({
                    "slug": p.slug, "title": p.title, "members": p.members.iter().map(member).collect::<Vec<_>>(),
                })).collect::<Vec<_>>(),
            })
        })
        .collect();
    let cmp: Vec<serde_json::Value> = comparison
        .iter()
        .map(|c| {
            serde_json::json!({
                "case": c.slug, "designation": c.designation, "family": c.family, "stations": c.stations,
                "worst_rel": { "y_t": c.y_t, "dy_t_dx": c.y_t_slope, "y_c": c.y_c, "dy_c_dx": c.y_c_slope, "surface": c.surface },
            })
        })
        .collect();
    fs::write(
        run_dir.join("summary.json"),
        serde_json::to_string_pretty(&serde_json::json!({
            "n_nodes": N_NODES, "series": series_json, "naca456_comparison": cmp,
            "validation_set": validation_set().iter().map(|v| serde_json::json!({
                "designation": v.designation, "series": v.series, "cli": v.cli, "why": v.why, "references": v.references,
            })).collect::<Vec<_>>(),
        }))
        .unwrap(),
    )
    .unwrap();
}

fn comparison_table_md(comparison: &[CaseComparison]) -> String {
    let mut t = String::from(
        "| Case | Section | Thickness form | Stations | worst Δy_t | worst Δ(dy_t/dx) | worst Δy_c | worst Δ(dy_c/dx) | worst Δ surface |\n|---|---|---|---:|---:|---:|---:|---:|---:|\n",
    );
    for c in comparison {
        t += &format!(
            "| `{}` | {} | {} | {} | {:.1e} | {:.1e} | {:.1e} | {:.1e} | {:.1e} |\n",
            c.slug, c.designation, c.family, c.stations, c.y_t, c.y_t_slope, c.y_c, c.y_c_slope, c.surface
        );
    }
    t
}

fn comparison_note() -> &'static str {
    "Differences are `|Δ| / max(|yFoil|, |naca456|, 1)`, the worst over naca456's 98 \"very fine\" stations. \
     The closed-form families agree to round-off. The 6-series mean lines differ by naca456's 10-digit π \
     (1.1e-10 relative). The 6-series thickness forms differ by naca456's own root tolerance: it finds the \
     station on the arc-length spline with Brent's method at 1e-6 and reports the ordinate at the station \
     reached, so its ordinates are off by up to 1e-6 × |dy_t/dx| (largest at the nose); yFoil inverts to \
     round-off. The gates in `tests/naca456_series_tests.rs` are derived from exactly that \
     (`tests/utilities/tolerances.rs`). naca456 reports the aft slope of the 4-digit modified form as \
     dy/d(1 − x); the sign is restored before comparing."
}

pub fn write_index(run_dir: &Path, series: &[&SeriesStudy], comparison: &[CaseComparison]) {
    let mut f = fs::File::create(run_dir.join("README.md")).unwrap();
    writeln!(f, "# Aerofoil series\n").unwrap();
    writeln!(
        f,
        "Generated by `cargo run --release -p aerofoil-series` (provenance in `metadata.json`, every drawn section's \
         geometry with its `generator` record under `<series>/<panel>/`, table data in `summary.json`). Each figure is \
         one generator family: one panel per parameter, the family default in black on top, the members behind it \
         coloured by parameter value (YlGnBu, lightest = smallest), {N_NODES} nodes each, all panels on the same axes \
         (x −0.2…1.2, y −0.5…0.5, equal scale).\n"
    )
    .unwrap();
    writeln!(
        f,
        "Figures are drawn by `plot.py` (matplotlib, via `scripts/figures/render.sh`) from `summary.json` and the \
         geometry files, at the document's physical size in its font (`scripts/figures/style.py`), and come as SVG \
         and PDF; include the PDF at natural size (`\\includegraphics{{...pdf}}`, no `width=`, no `\\resizebox`).\n"
    )
    .unwrap();
    writeln!(f, "| Figure | Family | Default (black) | Panels |\n|---|---|---|---|").unwrap();
    for s in series {
        writeln!(
            f,
            "| [{0}.svg]({0}.svg) | {1} | {2} | {3} |",
            s.slug,
            s.title,
            s.default.designation,
            s.panels.iter().map(|p| p.title.as_str()).collect::<Vec<_>>().join("; ")
        )
        .unwrap();
    }
    for s in series {
        writeln!(f, "\n## {}\n", s.title).unwrap();
        writeln!(f, "Parameters: {}.\n", s.parameters).unwrap();
        writeln!(f, "{}\n", s.description).unwrap();
        for p in &s.panels {
            writeln!(f, "### {}\n", p.title).unwrap();
            writeln!(
                f,
                "| Section | Parameter | Nodes | TE gap | Max thickness | File |\n|---|---|---:|---:|---:|---|"
            )
            .unwrap();
            for m in &p.members {
                writeln!(
                    f,
                    "| {} | {} | {} | {:.2e} | {:.4} | `{}/{}/{}.json` |",
                    m.designation,
                    m.label,
                    m.geometry.x.len(),
                    te_gap(&m.geometry),
                    max_thickness(&m.geometry),
                    s.slug,
                    p.slug,
                    m.slug
                )
                .unwrap();
            }
            writeln!(f).unwrap();
        }
    }
    if !comparison.is_empty() {
        writeln!(f, "\n## Generators against naca456\n").unwrap();
        writeln!(f, "{}\n", comparison_note()).unwrap();
        write!(f, "{}", comparison_table_md(comparison)).unwrap();
    }
}

fn tex_escape(s: &str) -> String {
    s.replace('_', "\\_")
        .replace('%', "\\%")
        .replace('&', "\\&")
        .replace('#', "\\#")
}

pub fn write_index_tex(run_dir: &Path, series: &[&SeriesStudy], comparison: &[CaseComparison]) {
    let mut f = fs::File::create(run_dir.join("README.tex")).unwrap();
    let w = |f: &mut fs::File, s: &str| writeln!(f, "{s}").unwrap();
    w(&mut f, "\\documentclass[11pt,a4paper]{article}");
    w(&mut f, "\\usepackage[margin=20mm]{geometry}");
    w(&mut f, "\\usepackage[utf8]{inputenc}");
    w(&mut f, "\\usepackage{amsmath,booktabs,longtable,siunitx,graphicx,url}");
    w(&mut f, "\\title{Aerofoil series}");
    w(
        &mut f,
        "\\author{yFoil project}\n\\date{\\today}\n\\begin{document}\n\\maketitle",
    );
    w(&mut f, &format!(
        "\\noindent Generated by \\texttt{{cargo run --release -p aerofoil-series}} (provenance in \\texttt{{metadata.json}}, \
         table data in \\texttt{{summary.json}}, every drawn section's geometry under \\texttt{{<series>/<panel>/}}). Each figure \
         is one generator family: one panel per parameter, the family default in black on top, the members behind it coloured \
         by parameter value (YlGnBu, lightest = smallest), {N_NODES} nodes each, all panels on the same axes \
         ($x$ from $-0.2$ to $1.2$, $y$ from $-0.5$ to $0.5$, equal scale)."
    ));
    w(
        &mut f,
        "\n\\section*{Figures}\n\\noindent Figures are drawn by \\texttt{plot.py} (matplotlib) at the document's \
         physical size in its font (\\texttt{scripts/figures/style.py}), so they are included at natural size: no \
         \\texttt{width=} and no \\texttt{\\resizebox}.",
    );
    for s in series {
        w(&mut f, &format!("\n\\section*{{{}}}", tex_escape(s.title)));
        w(
            &mut f,
            &format!("\\noindent Parameters: {}.\n", tex_escape(s.parameters)),
        );
        w(&mut f, &format!("\\noindent {}\n", tex_escape(s.description)));
        w(
            &mut f,
            &format!(
                "\\begin{{figure}}[p]\\centering\\includegraphics{{{}.pdf}}\\caption{{{}: {} nodes; default {} in black, \
                 members coloured by parameter value.}}\\end{{figure}}",
                s.slug,
                tex_escape(s.title),
                N_NODES,
                tex_escape(&s.default.designation)
            ),
        );
    }
    if !comparison.is_empty() {
        w(&mut f, "\n\\section*{Generators against naca456}");
        w(&mut f, &format!("\\noindent {}\n", tex_escape(comparison_note())));
        w(
            &mut f,
            "{\\renewcommand\\arraystretch{1.1}\\small\n\\begin{longtable}{@{}llrrrrrr@{}}\\toprule",
        );
        w(&mut f, "Case & Thickness form & Stations & $\\Delta y_t$ & $\\Delta y_t'$ & $\\Delta y_c$ & $\\Delta y_c'$ & $\\Delta$ surface \\\\ \\midrule\\endhead");
        for c in comparison {
            w(
                &mut f,
                &format!(
                    "{} & {} & {} & \\num{{{:.1e}}} & \\num{{{:.1e}}} & \\num{{{:.1e}}} & \\num{{{:.1e}}} & \\num{{{:.1e}}} \\\\",
                    tex_escape(&c.designation),
                    c.family,
                    c.stations,
                    c.y_t,
                    c.y_t_slope,
                    c.y_c,
                    c.y_c_slope,
                    c.surface
                ),
            );
        }
        w(&mut f, "\\bottomrule\\end{longtable}}");
    }
    w(&mut f, "\\end{document}");
}

/// The tracked documentation page: figures copied in, prose from the study definition, the
/// validation set, and the naca456 comparison table
pub fn write_docs(docs: &Path, run_dir: &Path, series: &[SeriesStudy], comparison: &[CaseComparison]) {
    fs::create_dir_all(docs).unwrap();
    for s in series {
        fs::copy(
            run_dir.join(format!("{}.svg", s.slug)),
            docs.join(format!("{}.svg", s.slug)),
        )
        .unwrap();
    }
    let mut f = fs::File::create(docs.join("README.md")).unwrap();
    writeln!(f, "# Aerofoil series\n").unwrap();
    writeln!(
        f,
        "Generated by `cargo run --release -p aerofoil-series -- --docs` from the generators in `src/geometry/series/` \
         and the naca456 fixtures in `tests/fixtures/naca456/` (figures drawn from the run's JSON by `plot.py`, \
         matplotlib); nothing on this page is hand-fed. One figure per \
         generator family: one panel per parameter, the family default (the validation set's member) in black on top, \
         the members that vary the parameter behind it coloured by value (YlGnBu, lightest = smallest), {N_NODES} nodes \
         each, every panel on the same axes (x from −0.2 to 1.2, y from −0.5 to 0.5, equal scale). The formulas and \
         the history of each family are in the [aerofoil series guide](../../guide/aerofoil-series.md); the \
         references in the [bibliography](../../references.md).\n"
    )
    .unwrap();

    writeln!(f, "## Selection of aerofoils\n").unwrap();
    writeln!(
        f,
        "The XFOIL-equivalence cases are run on one section per family (two from the 4-digit series). Each was chosen \
         for something the others do not exercise, and each is public, mathematically defined and reproducible from \
         its designation.\n"
    )
    .unwrap();
    writeln!(f, "| Section | Series | Why | Generate |\n|---|---|---|---|").unwrap();
    for v in validation_set() {
        let refs: Vec<String> = v
            .references
            .iter()
            .map(|r| format!("[{r}](../../references.md#{r})"))
            .collect();
        writeln!(
            f,
            "| {} | {} | {} ({}) | `{}` |",
            v.designation,
            v.series,
            v.why,
            refs.join(", "),
            v.cli
        )
        .unwrap();
    }
    for s in series {
        writeln!(f, "\n## {}\n", s.title).unwrap();
        writeln!(f, "Parameters: {}.\n", s.parameters).unwrap();
        writeln!(f, "{}\n", s.description).unwrap();
        writeln!(f, "**In the validation set:** {}\n", s.validation_use).unwrap();
        let refs: Vec<String> = s
            .references
            .iter()
            .map(|r| format!("[{r}](../../references.md#{r})"))
            .collect();
        writeln!(f, "References: {}.\n", refs.join(", ")).unwrap();
        writeln!(
            f,
            "![{}]({}.svg)\n\n*{}: default {} in black; {}.*\n",
            s.title,
            s.slug,
            s.title,
            s.default.designation,
            s.panels.iter().map(|p| p.title.as_str()).collect::<Vec<_>>().join("; ")
        )
        .unwrap();
    }
    if !comparison.is_empty() {
        writeln!(f, "\n## Generators against naca456\n").unwrap();
        writeln!(
            f,
            "The NACA generators are checked against the public-domain NASA/PDAS `naca456` program (Carmichael 2001, \
             the revision of the NASA Langley ordinate programs of TM X-3284, TM X-3069 and TM-4741), run by \
             `scripts/naca456-fixtures.sh` through a driver on its own modules at 17 significant figures. {}\n",
            comparison_note()
        )
        .unwrap();
        write!(f, "{}", comparison_table_md(comparison)).unwrap();
    }
}
