//! Instrumentation cross-check: the instrumented XFOIL reference against the pristine build.
//!
//! The instrumentation patch series (`xfoil/instrumentation/instrument/`) adds file dumps to the
//! reference; it must add nothing else. This study runs the pristine and the instrumented
//! double-precision XFOIL 6.99 builds on one identical OPER script — a NACA 0012 generated by
//! XFOIL's own `NACA` command (so both builds start from the same generator at the same
//! precision), swept upward through stall until the solver diverges — and compares the two builds
//! on XFOIL's *standard* outputs only: the `PACC` polar file (`F7.3/F9.4/F10.5`) and one `DUMP`
//! boundary-layer file per angle (`F9.5/F10.6`). The instrumented build's own high-precision
//! records are not read; the comparison is like for like at the precision XFOIL itself implements.
//!
//! Every invocation creates a dated folder `runs/<UTC datetime>/` next to this crate holding
//! `metadata.json` (git tag or `untagged`, commit sha, dirty flag, the reference build manifest,
//! the sha256 of both binaries and the study constants), one directory per build
//! (`pristine/`, `instrumented/`) with the OPER script, XFOIL's stdout, the polar file and the
//! per-angle dumps, then the post-processed products: `summary.json` (every value the plot
//! uses, plus the file-level comparison), `naca<foil>_check.svg` and `.pdf` (the 2×2 figure, drawn
//! from `summary.json` and nothing else at the document's physical size and font — see
//! `figure.rs`) and the `README.md` / `README.tex` index. `runs/` is gitignored.
//!
//! Usage (from the repository root, reference built with `cargo xtask xfoil-build`):
//!
//! ```text
//! cargo run --release -p xfoil-instrumentation-check -- [--foil 0012] [--npoints N]
//!                                                       [--resume RUN_DIR] [--plot-only RUN_DIR]
//! ```

mod plot;
mod run;
mod summary;

use std::path::{Path, PathBuf};

// ---------------------------------------------------------------------------------------------
// Study definition. These are the values to change; everything else follows from them.
// ---------------------------------------------------------------------------------------------

/// NACA 4-digit designation given to XFOIL's `NACA` command
pub const FOIL: &str = "0012";
/// Panel nodes: XFOIL's `PPAR` `N` (160 is also XFOIL's default)
pub const PANELS: usize = 160;
pub const REYNOLDS: f64 = 1.0e6;
pub const MACH: f64 = 0.0;
pub const NCRIT: f64 = 9.0;
pub const ITER: usize = 100;
/// Upward sweep: `ALPHA_START`, `+ ALPHA_STEP`, … for `NPOINTS` points (0° to 25°)
pub const ALPHA_START_DEG: f64 = 0.0;
pub const ALPHA_STEP_DEG: f64 = 0.5;
pub const NPOINTS: usize = 51;
/// Kill an XFOIL run after this long, or once its stdout has not grown for `STALL_SECS`: the
/// reference spins forever in its plot-label formatter once CL or CD is non-finite
/// (docs/xfoil-known-issues.md §4), and it prints a line per iteration until then
pub const RUN_TIMEOUT_SECS: u64 = 1800;
pub const STALL_SECS: u64 = 90;

/// The two reference builds under comparison
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Build {
    Pristine,
    Instrumented,
}

impl Build {
    pub const ALL: [Build; 2] = [Build::Pristine, Build::Instrumented];
    /// Directory name under the run folder and under `target/xfoil-ref/`
    pub fn slug(self) -> &'static str {
        match self {
            Build::Pristine => "pristine",
            Build::Instrumented => "instrumented",
        }
    }
    pub fn label(self) -> &'static str {
        match self {
            Build::Pristine => "XFOIL 6.99 DP, pristine",
            Build::Instrumented => "XFOIL 6.99 DP, instrumented",
        }
    }
    pub fn binary(self, root: &Path) -> PathBuf {
        root.join("target/xfoil-ref").join(self.slug()).join("bin/xfoil")
    }
}

/// The sweep's angles of attack, in degrees
pub fn alphas(npoints: usize) -> Vec<f64> {
    (0..npoints)
        .map(|i| ALPHA_START_DEG + i as f64 * ALPHA_STEP_DEG)
        .collect()
}

/// Repository root: this crate lives at scripts/xfoil-instrumentation-check
pub fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("repository root")
        .to_path_buf()
}

/// `runs/` next to this crate
pub fn runs_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("runs")
}

fn git(root: &Path, args: &[&str]) -> Option<String> {
    let out = std::process::Command::new("git")
        .args(args)
        .current_dir(root)
        .output()
        .ok()?;
    out.status
        .success()
        .then(|| String::from_utf8_lossy(&out.stdout).trim().to_string())
}

fn sha256(path: &Path) -> Option<String> {
    let out = std::process::Command::new("shasum")
        .args(["-a", "256"])
        .arg(path)
        .output()
        .ok()?;
    out.status.success().then(|| {
        String::from_utf8_lossy(&out.stdout)
            .split_whitespace()
            .next()
            .unwrap_or("")
            .to_string()
    })
}

/// UTC timestamp `YYYY-MM-DDTHH-MM-SSZ` (filesystem-safe), from the Unix time
fn utc_stamp() -> String {
    let secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_secs() as i64;
    let (days, rem) = (secs.div_euclid(86_400), secs.rem_euclid(86_400));
    let (h, m, s) = (rem / 3600, (rem % 3600) / 60, rem % 60);
    // civil-from-days (Howard Hinnant)
    let z = days + 719_468;
    let era = z.div_euclid(146_097);
    let doe = z - era * 146_097;
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let mo = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if mo <= 2 { y + 1 } else { y };
    format!("{y:04}-{mo:02}-{d:02}T{h:02}-{m:02}-{s:02}Z")
}

/// `metadata.json` of a run folder
pub fn write_metadata(run_dir: &Path, foil: &str, npoints: usize) {
    let root = repo_root();
    let sha = git(&root, &["rev-parse", "HEAD"]).unwrap_or_else(|| "unknown".into());
    let version = git(&root, &["describe", "--exact-match", "--tags", "HEAD"]).unwrap_or_else(|| "untagged".into());
    let dirty = git(&root, &["status", "--porcelain"])
        .map(|s| !s.is_empty())
        .unwrap_or(true);
    let reference: Vec<String> = std::fs::read_to_string(root.join("target/xfoil-ref/manifest.txt"))
        .unwrap_or_default()
        .lines()
        .map(str::to_string)
        .collect();
    let binaries: serde_json::Map<String, serde_json::Value> = Build::ALL
        .iter()
        .map(|b| {
            let p = b.binary(&root);
            (
                b.slug().to_string(),
                serde_json::json!({ "path": p.strip_prefix(&root).unwrap_or(&p).display().to_string(),
                                    "sha256": sha256(&p) }),
            )
        })
        .collect();
    let j = serde_json::json!({
        "study": "xfoil-instrumentation-check",
        "created_utc": run_dir.file_name().unwrap().to_string_lossy(),
        "version": version,
        "commit": sha,
        "dirty": dirty,
        "reference": reference,
        "binaries": binaries,
        "foil": format!("naca{foil}"),
        "conditions": { "panels": PANELS, "re": REYNOLDS, "mach": MACH, "ncrit": NCRIT, "iter": ITER,
                        "alpha_start_deg": ALPHA_START_DEG, "alpha_step_deg": ALPHA_STEP_DEG, "npoints": npoints },
        "procedure": "XFOIL NACA + PPAR N; OPER VISC/MACH/VPAR N/ITER; PACC on; ALFA then DUMP per point",
        "stall_secs": STALL_SECS,
        "timeout_secs": RUN_TIMEOUT_SECS,
    });
    std::fs::write(run_dir.join("metadata.json"), serde_json::to_string_pretty(&j).unwrap()).unwrap();
}

struct Args {
    foil: String,
    npoints: usize,
    /// An existing run folder to continue (builds already marked done are kept)
    resume: Option<PathBuf>,
    /// An existing run folder to post-process only (from its `summary.json`)
    plot_only: Option<PathBuf>,
}

fn parse_args() -> Args {
    let mut a = Args {
        foil: FOIL.to_string(),
        npoints: NPOINTS,
        resume: None,
        plot_only: None,
    };
    let argv: Vec<String> = std::env::args().skip(1).collect();
    let mut i = 0;
    while i < argv.len() {
        match argv[i].as_str() {
            "--foil" => {
                a.foil = argv[i + 1].clone();
                i += 1;
            }
            "--npoints" => {
                a.npoints = argv[i + 1].parse().expect("--npoints N");
                i += 1;
            }
            "--resume" => {
                a.resume = Some(PathBuf::from(&argv[i + 1]));
                i += 1;
            }
            "--plot-only" => {
                a.plot_only = Some(PathBuf::from(&argv[i + 1]));
                i += 1;
            }
            other => panic!("unknown argument {other}"),
        }
        i += 1;
    }
    a
}

fn main() {
    let args = parse_args();
    let root = repo_root();
    let run_dir = match (&args.plot_only, &args.resume) {
        (Some(d), _) => {
            assert!(d.join("summary.json").exists(), "{} has no summary.json", d.display());
            d.clone()
        }
        (None, Some(d)) => {
            std::fs::create_dir_all(d).unwrap();
            d.clone()
        }
        (None, None) => {
            let d = runs_root().join(utc_stamp());
            std::fs::create_dir_all(&d).unwrap();
            d
        }
    };

    if args.plot_only.is_none() {
        for b in Build::ALL {
            let x = b.binary(&root);
            assert!(
                x.exists(),
                "{} reference missing at {}: run `cargo xtask xfoil-build`",
                b.slug(),
                x.display()
            );
        }
        write_metadata(&run_dir, &args.foil, args.npoints);
        let alphas = alphas(args.npoints);
        // both builds at once, each in its own directory
        std::thread::scope(|scope| {
            for b in Build::ALL {
                let (root, run_dir, foil, alphas) = (&root, &run_dir, &args.foil, &alphas);
                scope.spawn(move || run::run_build(&b.binary(root), &run_dir.join(b.slug()), b, foil, alphas));
            }
        });
        // raw XFOIL files → summary.json. Nothing downstream reads the raw files.
        let results: Vec<run::BuildResult> = Build::ALL
            .iter()
            .map(|b| run::load(&run_dir.join(b.slug()), *b, &alphas))
            .collect();
        let s = summary::build(&args.foil, args.npoints, &results);
        std::fs::write(run_dir.join("summary.json"), serde_json::to_string_pretty(&s).unwrap()).unwrap();
    }

    // summary.json → plot and index (the only inputs of this stage)
    let s: summary::Summary =
        serde_json::from_str(&std::fs::read_to_string(run_dir.join("summary.json")).unwrap()).unwrap();
    let svg = run_dir.join(format!("naca{}_check.svg", s.foil));
    plot::draw(&svg, &s).unwrap();
    println!("wrote {}", svg.display());
    match figure_style::svg_to_pdf(&svg) {
        Ok(pdf) => println!("wrote {}", pdf.display()),
        Err(e) => println!("no PDF: {e}"),
    }
    summary::write_index(&run_dir, &s);
    summary::write_index_tex(&run_dir, &s);
    println!(
        "polar file identical: {}; BL dumps identical: {} of {}; stdout identical: {}",
        s.comparison.polar_identical,
        s.comparison.dumps_identical,
        s.comparison.dumps_compared,
        s.comparison.stdout_identical
    );
    println!("run folder: {}", run_dir.display());
}
