//! Repository automation: reference XFOIL build and fixture pipeline.
//!
//!   cargo xtask xfoil-build [--verify] [--snan]
//!   cargo xtask fixtures [--case NAME]... [--verify] [--big]
//!   cargo xtask coverage [--case NAME]... [--big] [--rebuild]   (docs/validation/coverage.md)
//!
//! The fixture pipeline enforces CLAUDE.md Rule 4 mechanically: geometry is generated by
//! yFoil, written at 17 significant digits, LOADed into instrumented XFOIL, and the panels
//! XFOIL dumps after ABCOPY must equal yFoil's bitwise before a run is accepted.

mod closures;
mod coverage;
mod cross_host;
mod noise_floor;
mod route;
mod steps;

use serde::Deserialize;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

#[derive(Debug, Deserialize)]
struct Cases {
    #[serde(rename = "case")]
    cases: Vec<Case>,
}

#[derive(Debug, Deserialize, Clone)]
struct Case {
    name: String,
    foil: String,
    n_nodes: usize,
    alphas: Vec<f64>,
    #[serde(default)]
    alphas_after_reinit: Vec<f64>,
    /// Drive the sweep with XFOIL's ASEQ (ALFA 0 / ASEQ a1 aN da / INIT / ALFA 0 / ASEQ ...)
    /// instead of one ALFA per point; ASEQ gives each point ITMAX+5 iterations, as the polar
    /// procedure does. `alphas_after_reinit` starts with the re-solved 0° that seeds the second leg.
    #[serde(default)]
    polar: bool,
    /// Fixed-CL points (OPER `CL x`), run after the alpha points
    #[serde(default)]
    cls: Vec<f64>,
    /// OPER `TYPE n`: MATYP = RETYP = n (Mach/Re dependence on CL); 0 = leave XFOIL's default (1)
    #[serde(default)]
    matyp: usize,
    /// Forced transition XTR xu xl (VPAR menu); empty = free transition
    #[serde(default)]
    xtr: Vec<f64>,
    /// OPER `DAMP`: modified envelope e^n amplification (IDAMP = 1)
    #[serde(default)]
    damp: bool,
    /// SETBL/UPDATE call numbers whose per-subroutine dumps to keep (default 1, 2, 3); the
    /// replay harness seeds from `mrchdu_input_<k>.dat` and checks `update_output_<k>.dat`
    #[serde(default)]
    dump_calls: Vec<usize>,
    /// Geometry-only case: XFOIL generates the airfoil itself (`airfoil = "xfoil-naca:0012"`,
    /// OPER never entered); the gate is the PANGEN dump against yFoil's XFOIL-model generator
    #[serde(default)]
    geometry_only: bool,
    /// PPAR parameters of a geometry-only case (GETPAN menu P, T, R, XT, XB), by their XFOIL
    /// names; absent = XFOIL's defaults, and the script is then unchanged
    #[serde(default)]
    ppar: Option<Ppar>,
    /// GDES `TGAP gap blend` on the LOADed panels (OPER never entered): the instrumented TGAP
    /// dumps the buffer airfoil before and after into `xfoil_tgap.dat`, the gate of
    /// `set_te_gap` (tests/subroutine/tgap.rs)
    #[serde(default)]
    tgap: Vec<f64>,
    #[serde(default)]
    re: f64,
    #[serde(default)]
    mach: f64,
    #[serde(default = "default_ncrit")]
    ncrit: f64,
    #[serde(default = "default_iter")]
    max_iterations: usize,
    #[serde(default)]
    track: bool,
    /// Inviscid only: no VISC, so ALFA is one SPECAL and CL one SPECCL (LVISC false throughout).
    /// There are no VISCAL records, so no +1-ULP twin is run; the gate is `events.dat`.
    #[serde(default)]
    inviscid: bool,
    /// Keep `events.dat`, the instrumented reference's branch-event log (`EVLOG`), for tests
    /// that compare yFoil's decisions with XFOIL's events
    #[serde(default)]
    events: bool,
    /// When non-empty, track exactly these files of the work directory besides the inputs
    /// (panels, manifest, xfoil.inp) — the files a test reads, and nothing else
    #[serde(default)]
    keep: Vec<String>,
    /// Cut the reference's closure log into `tests/fixtures/subroutines/` (`closures.rs`)
    #[serde(default)]
    closures: bool,
    /// How the case is tested (tests/execution/runs.rs): the whole run compared with XFOIL's
    #[serde(default)]
    run: bool,
    /// … through VISCAL call `run_through` only (0 = every call)
    #[serde(default)]
    run_through: usize,
    /// … and/or every iteration of these VISCAL calls replayed as a single step
    /// (tests/execution/steps.rs)
    #[serde(default)]
    step_calls: Vec<usize>,
    /// the study the case belongs to (`--group NAME` selects it): `branch-coverage`, `non-finite`,
    /// `series`, `known-issues`, `pathological` — the studies read their cases by it
    #[serde(default)]
    group: Option<String>,
    /// stop the reference after this many SETBL calls (`stop_after_setbl.txt`, patch 20): the
    /// deterministic end of a run whose march goes non-finite and would otherwise run for hours
    #[serde(default)]
    stop_after_setbl: Option<usize>,
    /// stop the reference on entering the first SETBL call whose BL state holds a NaN or an
    /// infinity (`stop_on_nonfinite.txt`, patch 20): a study that compares runs gains nothing
    /// from the iterations after that
    #[serde(default)]
    stop_on_nonfinite: bool,
    /// run the case's five seeded 1-ULP twins and write its `noise_floor.json` after the
    /// reference (study data, never tracked): whether XFOIL was ill-conditioned at each point of
    /// a validation run is known only from them
    #[serde(default)]
    twins: bool,
}
/// XFOIL's PPAR menu values for a geometry-only case
#[derive(Deserialize, serde::Serialize, Clone, Debug, Default)]
struct Ppar {
    cvpar: Option<f64>,
    cterat: Option<f64>,
    ctrrat: Option<f64>,
    xsref: Option<[f64; 2]>,
    xpref: Option<[f64; 2]>,
}

impl Ppar {
    /// The GETPAN lines that set the parameters, before the blank that runs PANGEN
    fn script_lines(&self) -> String {
        let mut s = String::new();
        if let Some(v) = self.cvpar {
            s += &format!("P {v}\n");
        }
        if let Some(v) = self.cterat {
            s += &format!("T {v}\n");
        }
        if let Some(v) = self.ctrrat {
            s += &format!("R {v}\n");
        }
        if let Some([a, b]) = self.xsref {
            s += &format!("XT {a} {b}\n");
        }
        if let Some([a, b]) = self.xpref {
            s += &format!("XB {a} {b}\n");
        }
        s
    }
}

impl Case {
    /// Case selection shared by `fixtures` and `coverage`: the `--case NAME`s, else the members of
    /// `--group NAME`, else every tracked case (`--big` adds the untracked ones, except the
    /// `pathological` group, which runs only by name or `--group pathological`).
    pub(crate) fn selected(&self, cases: &[&str], group: Option<&str>, big: bool) -> bool {
        if !cases.is_empty() {
            return cases.contains(&self.name.as_str());
        }
        if let Some(g) = group {
            return self.group.as_deref() == Some(g);
        }
        // the pathological cases run only when asked for by name or group
        if self.group.as_deref() == Some("pathological") {
            return false;
        }
        self.track || big
    }
}

/// How a watched reference run ended.
#[derive(Debug, PartialEq)]
pub(crate) enum RunEnd {
    /// it exited on its own
    Finished,
    /// its output stopped growing for two minutes — XFOIL's plot-label loop on a non-finite value
    /// (known issues §4), a fixed point of the run — and it was ended there
    Hung,
    /// still running after an hour: a case that needs a deterministic end (`stop_on_nonfinite` or
    /// `stop_after_setbl`, instrumentation patch 20) and has none
    TimedOut,
}

/// Run the reference in `dir` on its `xfoil.inp`, writing `stdout.txt`, under a watchdog. Where a
/// run ends is decided by the run itself, never by the clock: it finishes, it hangs (ended after
/// two minutes without output, at a fixed point), or the case asks the reference to stop itself
/// (patch 20). A run is ended with SIGTERM first — the gcov build writes its counters on it
/// (`scripts/xfoil-build/gcov_flush.c`) — and SIGKILL only if it is still there after ten
/// seconds; the records written so far are kept either way.
pub(crate) fn run_xfoil(xfoil: &Path, dir: &Path) -> Result<RunEnd, String> {
    const STALL_SECONDS: u64 = 120;
    const LIMIT_SECONDS: u64 = 3600;
    let inp = fs::File::open(dir.join("xfoil.inp")).map_err(|e| e.to_string())?;
    let out_path = dir.join("stdout.txt");
    let out = fs::File::create(&out_path).map_err(|e| e.to_string())?;
    let mut child = Command::new(xfoil)
        .current_dir(dir)
        .stdin(inp)
        .stdout(out)
        .stderr(Stdio::inherit())
        .spawn()
        .map_err(|e| format!("spawn xfoil: {e}"))?;
    let end = |child: &mut std::process::Child| {
        let _ = Command::new("kill").args(["-TERM", &child.id().to_string()]).status();
        for _ in 0..20 {
            if matches!(child.try_wait(), Ok(Some(_))) {
                return;
            }
            std::thread::sleep(std::time::Duration::from_millis(500));
        }
        let _ = child.kill();
        let _ = child.wait();
    };
    let mut last_len = 0u64;
    let mut last_growth = std::time::Instant::now();
    let started = std::time::Instant::now();
    loop {
        if let Some(st) = child.try_wait().map_err(|e| e.to_string())? {
            return if st.success() {
                Ok(RunEnd::Finished)
            } else {
                Err(format!("xfoil exited {st}"))
            };
        }
        std::thread::sleep(std::time::Duration::from_millis(500));
        let len = fs::metadata(&out_path).map(|m| m.len()).unwrap_or(0);
        if len != last_len {
            last_len = len;
            last_growth = std::time::Instant::now();
        } else if last_growth.elapsed().as_secs() >= STALL_SECONDS {
            end(&mut child);
            return Ok(RunEnd::Hung);
        }
        if started.elapsed().as_secs() >= LIMIT_SECONDS {
            end(&mut child);
            return Ok(RunEnd::TimedOut);
        }
    }
}

fn default_ncrit() -> f64 {
    9.0
}
fn default_iter() -> usize {
    20
}

fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .to_path_buf()
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    match args.first().map(String::as_str) {
        Some("xfoil-build") => xfoil_build(&args[1..]),
        Some("fixtures") => fixtures(&args[1..]),
        Some("coverage") => coverage::run(&args[1..]),
        Some("twins") => steps::twins(&args[1..]),
        Some("steps") => steps::steps(&args[1..]),
        Some("route") => route::route(&args[1..]),
        Some("cross-host") => cross_host::run(&args[1..]),
        _ => {
            eprintln!(
                "usage: cargo xtask <xfoil-build [--verify] [--snan] | fixtures [--case NAME] [--group NAME] [--verify] [--audit] [--big] | coverage [--case NAME] [--group NAME] [--with-group NAME] [--big] [--rebuild] [--per-case] | twins --case NAME | steps [--case NAME] [--from-json] | route [--case NAME] [--reuse] | cross-host [--out PATH]>"
            );
            std::process::exit(2);
        }
    }
}

fn xfoil_build(flags: &[String]) {
    let st = Command::new(root().join("scripts/xfoil-build.sh"))
        .args(flags)
        .status()
        .expect("run scripts/xfoil-build.sh");
    if !st.success() {
        std::process::exit(st.code().unwrap_or(1));
    }
}

fn fixtures(flags: &[String]) {
    let root = root();
    if flags.iter().any(|f| f == "--audit") {
        if flags.iter().any(|f| f == "--by-test") {
            audit_by_test(&root);
        } else {
            audit(&root);
        }
        return;
    }
    let verify = flags.iter().any(|f| f == "--verify");
    let big = flags.iter().any(|f| f == "--big");
    let inputs_only = flags.iter().any(|f| f == "--inputs-only");
    let selected: Vec<&str> = flags
        .windows(2)
        .filter(|w| w[0] == "--case")
        .map(|w| w[1].as_str())
        .collect();

    let mut cases: Cases = toml::from_str(
        &fs::read_to_string(root.join("xtask/fixtures-config/cases.toml")).expect("xtask/fixtures-config/cases.toml"),
    )
    .expect("parse cases.toml");
    steps::apply_cover(&root, &mut cases.cases);
    let xfoil = root.join("target/xfoil-ref/instrumented/bin/xfoil");
    if !xfoil.exists() {
        xfoil_build(&[]);
    }
    let yfoil = root.join("target/debug/yfoil");
    run(
        Command::new("cargo")
            .args(["build", "-q", "--bin", "yfoil"])
            .current_dir(&root),
        "cargo build yfoil",
    );
    let ref_manifest = fs::read_to_string(root.join("target/xfoil-ref/manifest.txt")).unwrap_or_default();

    let mut failures = 0;
    let group: Option<&str> = flags.windows(2).find(|w| w[0] == "--group").map(|w| w[1].as_str());
    // a deterministic stop cuts a run off before the branches only reached later — the
    // non-finite fallbacks among them — so no case that gates or measures branches may have one,
    // nor a known-issues case, whose run's own end (a hang, a halt) is what it shows
    for case in &cases.cases {
        let gates = case.track
            || matches!(
                case.group.as_deref(),
                Some("branch-coverage" | "non-finite" | "series" | "known-issues")
            );
        if gates && (case.stop_on_nonfinite || case.stop_after_setbl.is_some()) {
            eprintln!(
                "{}: a case that gates or measures branches must run to its natural end; remove `stop_on_nonfinite` / `stop_after_setbl`",
                case.name
            );
            std::process::exit(1);
        }
    }
    for case in &cases.cases {
        if !case.selected(&selected, group, big) {
            continue;
        }
        println!("== {} ==", case.name);
        let work = root.join("target/fixtures").join(&case.name);
        // the case's twins (`cargo xtask twins`, study data) are set aside and put back if the
        // regenerated run has the same inputs, so regenerating does not discard them
        let held = root.join("target/fixtures/.held").join(&case.name);
        let _ = fs::remove_dir_all(&held);
        if work.join("noise_floor.json").exists() {
            fs::create_dir_all(&held).unwrap();
            for e in fs::read_dir(&work).unwrap().flatten() {
                let n = e.file_name().to_string_lossy().to_string();
                if n.starts_with("ulp")
                    || [
                        "noise_floor.json",
                        "panels.dat",
                        "xfoil.inp",
                        "stop_after_setbl.txt",
                        "stop_on_nonfinite.txt",
                    ]
                    .contains(&n.as_str())
                {
                    let _ = fs::rename(e.path(), held.join(&n));
                }
            }
        }
        let _ = fs::remove_dir_all(&work);
        fs::create_dir_all(&work).unwrap();

        if case.geometry_only {
            // XFOIL's own NACA generator and PANGEN: `NACA dddd` (which calls PANGEN with the
            // default NPAN) then `PPAR / N n` to repanel at the case's n_nodes
            let (kind, spec) = case.foil.split_once(':').expect("airfoil = \"xfoil-naca:0012\"");
            assert_eq!(kind, "xfoil-naca", "geometry_only cases use xfoil-naca:<digits>");
            let ppar = case.ppar.as_ref().map(Ppar::script_lines).unwrap_or_default();
            let script = format!("PLOP\nG F\n\nNACA {spec}\nPPAR\nN {}\n{ppar}\n\n\nQUIT\n", case.n_nodes);
            fs::write(work.join("xfoil.inp"), &script).unwrap();
            let inp = fs::File::open(work.join("xfoil.inp")).unwrap();
            let out = fs::File::create(work.join("stdout.txt")).unwrap();
            let st = Command::new(&xfoil)
                .current_dir(&work)
                .stdin(inp)
                .stdout(out)
                .stderr(Stdio::inherit())
                .status()
                .expect("run xfoil");
            if !st.success() || !work.join("xfoil_pangen.dat").exists() {
                eprintln!("  xfoil geometry run failed: {st}");
                failures += 1;
                continue;
            }
            let manifest = serde_json::json!({
                "case": { "name": case.name, "foil": case.foil, "n_nodes": case.n_nodes, "geometry_only": true, "ppar": case.ppar },
                "xfoil_ref": ref_manifest.lines().collect::<Vec<_>>(),
                "generated_by": "cargo xtask fixtures",
            });
            fs::write(
                work.join("manifest.json"),
                serde_json::to_string_pretty(&manifest).unwrap(),
            )
            .unwrap();
            if case.track {
                let dst = root.join("tests/fixtures/xfoil").join(&case.name);
                let staged: Vec<(PathBuf, Vec<u8>)> = ["manifest.json", "xfoil.inp", "xfoil_pangen.dat"]
                    .iter()
                    .map(|n| (dst.join(n), fs::read(work.join(n)).unwrap()))
                    .collect();
                if verify {
                    let mut diffs = 0;
                    for (p, b) in &staged {
                        if p.file_name().unwrap() == "manifest.json" {
                            continue;
                        }
                        if fs::read(p).ok().as_deref() != Some(b.as_slice()) {
                            eprintln!("  DIFFERS: {}", p.display());
                            diffs += 1;
                        }
                    }
                    if diffs > 0 {
                        failures += 1;
                    } else {
                        println!("  verify: {} tracked files byte-identical", staged.len() - 1);
                    }
                } else {
                    fs::create_dir_all(&dst).unwrap();
                    for (p, b) in &staged {
                        fs::write(p, b).unwrap();
                    }
                    println!("  tracked {} files -> {}", staged.len(), dst.display());
                }
            }
            continue;
        }

        // 1. geometry, by yFoil only: `naca4:dddd[:sharp]` (the original 4-digit cases),
        // `naca:<designation>[:sharp]` for any NACA family (`yfoil geometry naca`), or
        // `karman-trefftz`, the analytic section at the generator's defaults (sharp TE)
        let mut parts = case.foil.split(':');
        let kind = parts.next().unwrap();
        // `--method cosine`: the analytic cosine sampling every tracked fixture was generated
        // with (the CLI's default is now PANGEN)
        let npan = case.n_nodes.to_string();
        let mut gargs: Vec<&str> = vec!["geometry"];
        if kind == "karman-trefftz" {
            assert!(parts.next().is_none(), "foil = \"karman-trefftz\" takes no parameters");
            gargs.extend(["karman-trefftz", "-n", &npan, "--method", "cosine", "-o", "panels.json"]);
        } else {
            let spec = parts.next().expect("airfoil = \"naca4:0012[:sharp]\"");
            let sharp = matches!(parts.next(), Some("sharp"));
            assert!(
                kind == "naca4" || kind == "naca",
                "foil kinds: naca4:<4 digits>, naca:<designation>, karman-trefftz, xfoil-naca:<digits> (geometry_only)"
            );
            gargs.extend(["naca", spec, "-n", &npan, "--method", "cosine", "-o", "panels.json"]);
            if sharp {
                gargs.push("--sharp");
            }
        }
        run(Command::new(&yfoil).args(&gargs).current_dir(&work), "yfoil geometry");
        run(
            Command::new(&yfoil)
                .args([
                    "geometry",
                    "convert",
                    "panels.json",
                    "--to",
                    "dat",
                    "--name",
                    &case.name,
                    "-o",
                    "panels.dat",
                ])
                .current_dir(&work),
            "yfoil geometry convert",
        );

        // 2. XFOIL script: LOAD (never NACA/PANE/PPAR), pinned defaults, alpha sequence.
        // A TGAP case enters GDES instead of OPER and leaves after the one command.
        let mut s = String::from("PLOP\nG F\n\nLOAD panels.dat\n");
        if !case.tgap.is_empty() {
            assert_eq!(case.tgap.len(), 2, "tgap = [gap, blend]");
            s += &format!("GDES\nTGAP {} {}\n\nQUIT\n", case.tgap[0], case.tgap[1]);
        }
        let geometry_case = !case.tgap.is_empty();
        if !geometry_case {
            s += "OPER\n";
        }
        if geometry_case {
            fs::write(work.join("xfoil.inp"), &s).unwrap();
        }
        if !geometry_case {
            let xtr = if case.xtr.is_empty() {
                String::new()
            } else {
                assert_eq!(case.xtr.len(), 2, "xtr = [xu, xl]");
                format!("XTR {} {}\n", case.xtr[0], case.xtr[1])
            };
            if case.inviscid {
                assert!(
                    case.xtr.is_empty() && !case.damp && !case.polar && case.alphas_after_reinit.is_empty(),
                    "inviscid cases take MACH, TYPE, alphas and cls only"
                );
                s += &format!("MACH {}\n", case.mach);
            } else {
                s += &format!(
                    "VISC {}\nMACH {}\nVPAR\nN {}\n{xtr}\nITER {}\n",
                    case.re, case.mach, case.ncrit, case.max_iterations
                );
            }
            if case.matyp != 0 {
                s += &format!("TYPE {}\n", case.matyp);
            }
            if case.damp {
                s += "DAMP\n";
            }
            let seq = |s: &mut String, alphas: &[f64]| {
                // ALFA for the first point, ASEQ for the rest (uniform step asserted)
                s.push_str(&format!("ALFA {}\n", alphas[0]));
                if alphas.len() > 1 {
                    let da = alphas[1] - alphas[0];
                    for w in alphas.windows(2) {
                        assert!(
                            ((w[1] - w[0]) - da).abs() < 1e-12,
                            "polar alphas must be uniformly spaced"
                        );
                    }
                    s.push_str(&format!("ASEQ {} {} {}\n", alphas[1], alphas[alphas.len() - 1], da));
                }
            };
            if case.polar {
                seq(&mut s, &case.alphas);
                if !case.alphas_after_reinit.is_empty() {
                    s += "INIT\n";
                    seq(&mut s, &case.alphas_after_reinit);
                }
            } else if case.inviscid {
                for a in &case.alphas {
                    s += &format!("ALFA {a}\n");
                }
            } else {
                for a in &case.alphas {
                    s += &format!("ALFA {a}\nCPWR cp_a{a}.dat\nDUMP bl_a{a}.dat\n");
                }
                if !case.alphas_after_reinit.is_empty() {
                    s += "INIT\n";
                    for a in &case.alphas_after_reinit {
                        s += &format!("ALFA {a}\nCPWR cp_a{a}.dat\nDUMP bl_a{a}.dat\n");
                    }
                }
            }
            for c in &case.cls {
                s += &format!("CL {c}\n");
            }
            s += "\nQUIT\n";
            fs::write(work.join("xfoil.inp"), &s).unwrap();
        }
        // `--inputs-only`: the panels and the script, for a measurement that runs its own reference
        // (`cargo xtask coverage`); the instrumented reference is not run
        if inputs_only {
            println!("  inputs written");
            continue;
        }
        let _ = fs::remove_file(work.join("stop_after_setbl.txt"));
        if let Some(n) = case.stop_after_setbl {
            fs::write(work.join("stop_after_setbl.txt"), format!("{n}\n")).unwrap();
        }
        let _ = fs::remove_file(work.join("stop_on_nonfinite.txt"));
        if case.stop_on_nonfinite {
            fs::write(work.join("stop_on_nonfinite.txt"), "").unwrap();
        }
        // the closure log (patch 21) only for the cases whose closure fixtures are cut from it
        let _ = fs::remove_file(work.join("log_closures.txt"));
        if case.closures {
            fs::write(work.join("log_closures.txt"), "").unwrap();
        }
        // whether the watchdog ended a reference run of this case (recorded in the manifest)
        let hung = std::cell::Cell::new(false);
        let run_reference = |dump_calls: &[usize]| -> bool {
            let _ = fs::remove_file(work.join("dump_calls.txt"));
            if !dump_calls.is_empty() {
                let list: Vec<String> = dump_calls.iter().map(|k| k.to_string()).collect();
                fs::write(work.join("dump_calls.txt"), list.join("\n") + "\n").unwrap();
            }
            match run_xfoil(&xfoil, &work) {
                Ok(RunEnd::Finished) => true,
                Ok(RunEnd::Hung) => {
                    eprintln!("  WATCHDOG: xfoil stopped producing output (hung) and was ended; the records written so far are kept");
                    hung.set(true);
                    true
                }
                Ok(RunEnd::TimedOut) => {
                    eprintln!("  xfoil still running after an hour: give the case a deterministic end (`stop_on_nonfinite` or `stop_after_setbl`)");
                    false
                }
                Err(e) => {
                    eprintln!("  {e}");
                    false
                }
            }
        };
        if !run_reference(&case.dump_calls) {
            failures += 1;
            continue;
        }
        // a case whose calls are replayed step by step needs every SETBL call of them dumped,
        // which needs the calls' iteration counts: rerun with the full list
        let mut case = case.clone();
        if !case.step_calls.is_empty() {
            let (calls, files) = steps::step_call_files(&work, &case.step_calls);
            for k in calls {
                if !case.dump_calls.contains(&k) {
                    case.dump_calls.push(k);
                }
            }
            case.dump_calls.sort_unstable();
            for f in files {
                if !case.keep.contains(&f) {
                    case.keep.push(f);
                }
            }
            if !run_reference(&case.dump_calls) {
                failures += 1;
                continue;
            }
        }
        if case.run && !case.inviscid {
            for f in ["viscal_points.dat", "viscal_iters_all.dat"] {
                if !case.keep.iter().any(|k| k == f) {
                    case.keep.push(f.to_string());
                }
            }
        }
        let case = &case;

        // 3. bitwise geometry handoff (Rule 4)
        match check_handoff(&work) {
            Ok(n) => println!("  handoff: {n} nodes bitwise identical"),
            Err(e) => {
                eprintln!("  HANDOFF FAILED: {e}");
                failures += 1;
                continue;
            }
        }
        let mut twins_ready = false;
        if held.join("noise_floor.json").exists() {
            let same = |f: &str| fs::read(held.join(f)).ok() == fs::read(work.join(f)).ok();
            if same("panels.dat") && same("xfoil.inp") && same("stop_after_setbl.txt") && same("stop_on_nonfinite.txt")
            {
                for e in fs::read_dir(&held).unwrap().flatten() {
                    let n = e.file_name().to_string_lossy().to_string();
                    if n.starts_with("ulp") || n == "noise_floor.json" {
                        let _ = fs::rename(e.path(), work.join(&n));
                    }
                }
                println!("  twins kept (same panels and script)");
                twins_ready = true;
            } else {
                println!(
                    "  twins discarded (the inputs changed): rerun `cargo xtask twins --case {}`",
                    case.name
                );
            }
            let _ = fs::remove_dir_all(&held);
        }
        if case.twins && !twins_ready {
            match steps::run_twins(&xfoil, &work, case.inviscid) {
                Ok(summary) => println!("  twins: {summary}"),
                Err(e) => {
                    eprintln!("  TWINS FAILED: {e}");
                    failures += 1;
                }
            }
        }

        // 3b. a TGAP case must have produced its dump. (The reference's twins, which the step
        // cover is chosen from, are `cargo xtask twins`; no tracked fixture records them.)
        if geometry_case && !work.join("xfoil_tgap.dat").exists() {
            eprintln!("  xfoil_tgap.dat missing (TGAP dump)");
            failures += 1;
            continue;
        }

        // 4. manifest
        let manifest = serde_json::json!({
            "case": { "name": case.name, "foil": case.foil, "n_nodes": case.n_nodes, "alphas": case.alphas,
                      "alphas_after_reinit": case.alphas_after_reinit, "re": case.re, "mach": case.mach,
                      "ncrit": case.ncrit, "max_iterations": case.max_iterations, "polar": case.polar, "cls": case.cls, "matyp": case.matyp, "xtr": case.xtr, "damp": case.damp, "dump_calls": case.dump_calls, "tgap": case.tgap,
                      "inviscid": case.inviscid, "events": case.events, "keep": case.keep, "closures": case.closures,
                      "run": case.run, "run_through": case.run_through, "step_calls": case.step_calls },
            "panels_dat_sha256": sha256(&work.join("panels.dat")),
            "xfoil_ref": ref_manifest.lines().collect::<Vec<_>>(),
            "generated_by": "cargo xtask fixtures",
        });
        let mut manifest = manifest;
        if let Some(n) = case.stop_after_setbl {
            manifest["case"]["stop_after_setbl"] = serde_json::json!(n);
        }
        if case.stop_on_nonfinite {
            manifest["case"]["stop_on_nonfinite"] = serde_json::json!(true);
        }
        // written only when it happened, so the manifest of every run that ends on its own is
        // unchanged; the studies read it (the plot-label hang, known issues §4)
        if hung.get() {
            manifest["truncated_by_watchdog"] = serde_json::json!(true);
        }
        fs::write(
            work.join("manifest.json"),
            serde_json::to_string_pretty(&manifest).unwrap(),
        )
        .unwrap();

        // 4b. closure fixtures, cut from the reference's subroutine log
        if case.closures && !verify {
            match closures::write(
                &case.name,
                &work,
                &root.join("tests/fixtures/subroutines"),
                &ref_manifest,
            ) {
                Ok(counts) => println!("  closure fixtures: {counts}"),
                Err(e) => {
                    eprintln!("  CLOSURE FIXTURES FAILED: {e}");
                    failures += 1;
                    continue;
                }
            }
        }

        // 5. track or verify
        if case.track {
            let dst = root.join("tests/fixtures/xfoil").join(&case.name);
            let mut staged: Vec<(PathBuf, Vec<u8>)> = vec![];
            // the inputs (checked against each other by tests/apparatus/inputs.rs), then exactly
            // the files the case's tests read (`keep`, and `events.dat` when `events`)
            if case.keep.is_empty() && !case.events && !case.closures {
                eprintln!("  a tracked case must name the files its tests read (`keep`)");
                failures += 1;
                continue;
            }
            for name in ["panels.json", "panels.dat", "manifest.json", "xfoil.inp"]
                .iter()
                .copied()
                .chain(case.keep.iter().map(String::as_str))
                .chain(case.events.then_some("events.dat"))
            {
                let p = work.join(name);
                if p.exists() {
                    staged.push((dst.join(name), fs::read(&p).unwrap()));
                } else if case.keep.iter().any(|k| k == name) {
                    eprintln!("  {name} (in `keep`) was not produced");
                    failures += 1;
                }
            }
            let total: u64 = staged.iter().map(|(_, b)| b.len() as u64).sum();
            // no size cap: what is tracked is what the tests read (`--audit` enforces it)
            println!("  {} files, {:.2} MB", staged.len(), total as f64 / 1048576.0);
            if verify {
                let mut diffs = 0;
                for (p, b) in &staged {
                    // manifest carries host/toolchain lines and may legitimately differ across hosts
                    if p.file_name().unwrap() == "manifest.json" {
                        continue;
                    }
                    if fs::read(p).ok().as_deref() != Some(b.as_slice()) {
                        eprintln!("  DIFFERS: {}", p.display());
                        diffs += 1;
                    }
                }
                if diffs > 0 {
                    failures += 1;
                } else {
                    println!("  verify: {} tracked files byte-identical", staged.len() - 1);
                }
            } else {
                let _ = fs::remove_dir_all(&dst);
                fs::create_dir_all(&dst).unwrap();
                for (p, b) in &staged {
                    fs::write(p, b).unwrap();
                }
                println!(
                    "  tracked {} files ({} bytes) -> {}",
                    staged.len(),
                    total,
                    dst.strip_prefix(&root).unwrap().display()
                );
            }
        } else {
            println!("  kept in {}", work.strip_prefix(&root).unwrap().display());
        }
    }
    if failures > 0 {
        eprintln!("{failures} case(s) failed");
        std::process::exit(1);
    }
}

/// Parse xfoil_panels.dat (ABCOPY dump, ES24.16) and compare bitwise against panels.json.
fn check_handoff(work: &Path) -> Result<usize, String> {
    #[derive(Deserialize)]
    struct Geom {
        x: Vec<f64>,
        y: Vec<f64>,
    }
    let g: Geom = serde_json::from_str(&fs::read_to_string(work.join("panels.json")).map_err(|e| e.to_string())?)
        .map_err(|e| e.to_string())?;
    let dump = fs::read_to_string(work.join("xfoil_panels.dat"))
        .map_err(|_| "xfoil_panels.dat missing (ABCOPY dump)".to_string())?;
    let mut n = 0;
    for line in dump.lines() {
        let p: Vec<&str> = line.split_whitespace().collect();
        if p.len() != 7 || p[0].parse::<usize>().is_err() {
            continue;
        }
        let i: usize = p[0].parse().unwrap();
        let (x, y): (f64, f64) = (p[1].parse().map_err(|_| "bad x")?, p[2].parse().map_err(|_| "bad y")?);
        if i == 0 || i > g.x.len() {
            return Err(format!("node index {i} out of range"));
        }
        if x.to_bits() != g.x[i - 1].to_bits() || y.to_bits() != g.y[i - 1].to_bits() {
            return Err(format!(
                "node {i}: xfoil=({x:e},{y:e}) yfoil=({:e},{:e})",
                g.x[i - 1],
                g.y[i - 1]
            ));
        }
        n += 1;
    }
    if n != g.x.len() {
        return Err(format!("xfoil dumped {n} nodes, yfoil has {}", g.x.len()));
    }
    Ok(n)
}

fn sha256(p: &Path) -> String {
    let out = Command::new("shasum")
        .args(["-a", "256"])
        .arg(p)
        .output()
        .expect("shasum");
    String::from_utf8_lossy(&out.stdout)
        .split_whitespace()
        .next()
        .unwrap_or("")
        .to_string()
}

fn run(cmd: &mut Command, what: &str) {
    let st = cmd.status().unwrap_or_else(|e| panic!("{what}: {e}"));
    if !st.success() {
        eprintln!("{what} failed: {st}");
        std::process::exit(1);
    }
}

/// `cargo xtask fixtures --audit`: every tracked file under `tests/fixtures/` must be read by some
/// test (CLAUDE.md Rule 7: committing a fixture is a decision, and the decision is that a test
/// needs it). Each tracked file's access time is set to 2000-01-01, the whole suite runs, and any
/// file whose access time did not move was read by nothing. Works wherever reads update access
/// times (macOS APFS; Linux `relatime`, since the old atime predates the file's mtime).
fn audit(root: &Path) {
    let out = Command::new("git")
        .args(["ls-files", "-z", "tests/fixtures"])
        .current_dir(root)
        .output()
        .expect("git ls-files");
    let files: Vec<PathBuf> = String::from_utf8_lossy(&out.stdout)
        .split('\0')
        .filter(|f| !f.is_empty() && !f.ends_with(".rs") && !f.ends_with("README.md"))
        .map(|f| root.join(f))
        .collect();
    let stamp = std::time::SystemTime::UNIX_EPOCH + std::time::Duration::from_secs(946_684_800);
    for chunk in files.chunks(500) {
        run(
            Command::new("touch").args(["-a", "-t", "200001010000"]).args(chunk),
            "touch -a",
        );
    }
    run(
        Command::new("cargo")
            .args(["test", "--all-targets", "--all-features", "-q"])
            .current_dir(root),
        "cargo test",
    );
    let mut unread: Vec<String> = vec![];
    let mut bytes = (0u64, 0u64);
    for f in &files {
        let m = fs::metadata(f).unwrap();
        bytes.0 += m.len();
        let accessed = m.accessed().unwrap();
        if accessed <= stamp + std::time::Duration::from_secs(60) {
            bytes.1 += m.len();
            unread.push(f.strip_prefix(root).unwrap().display().to_string());
        }
    }
    println!(
        "audit: {} tracked fixture files, {:.2} MB; {} unread ({:.2} MB)",
        files.len(),
        bytes.0 as f64 / 1048576.0,
        unread.len(),
        bytes.1 as f64 / 1048576.0
    );
    for u in &unread {
        println!("  unread: {u}");
    }
    if !unread.is_empty() {
        std::process::exit(1);
    }
}

/// `cargo xtask fixtures --audit --by-test`: which test reads which tracked fixture file. Every
/// integration test runs on its own, with the fixture files' access times reset before it, and the
/// files it opened are recorded: `target/audit/readers.json`, `{ "<file>": ["<binary>::<test>", …] }`
/// (the binary is the test category, `docs/conventions/testing.md`). A file no test opens has an
/// empty list.
fn audit_by_test(root: &Path) {
    let out = Command::new("git")
        .args(["ls-files", "-z", "tests/fixtures"])
        .current_dir(root)
        .output()
        .expect("git ls-files");
    let files: Vec<PathBuf> = String::from_utf8_lossy(&out.stdout)
        .split('\0')
        .filter(|f| !f.is_empty() && !f.ends_with(".rs") && !f.ends_with("README.md"))
        .map(|f| root.join(f))
        .collect();
    let stamp = std::time::SystemTime::UNIX_EPOCH + std::time::Duration::from_secs(946_684_800);
    let reset = || {
        for chunk in files.chunks(500) {
            run(
                Command::new("touch").args(["-a", "-t", "200001010000"]).args(chunk),
                "touch -a",
            );
        }
    };
    // the integration-test binaries, one per category
    let build = Command::new("cargo")
        .args([
            "test",
            "--release",
            "--tests",
            "--all-features",
            "--no-run",
            "--message-format=json",
        ])
        .current_dir(root)
        .stderr(Stdio::inherit())
        .output()
        .expect("cargo test --no-run");
    assert!(build.status.success(), "cargo test --no-run failed");
    let mut binaries: Vec<(String, PathBuf)> = vec![];
    for l in String::from_utf8_lossy(&build.stdout).lines() {
        let Ok(v) = serde_json::from_str::<serde_json::Value>(l) else {
            continue;
        };
        if v["target"]["kind"]
            .as_array()
            .is_some_and(|k| k.iter().any(|x| x == "test"))
        {
            if let Some(exe) = v["executable"].as_str() {
                binaries.push((v["target"]["name"].as_str().unwrap().to_string(), PathBuf::from(exe)));
            }
        }
    }
    let mut readers: std::collections::BTreeMap<String, Vec<String>> = files
        .iter()
        .map(|f| (f.strip_prefix(root).unwrap().display().to_string(), vec![]))
        .collect();
    for (name, exe) in &binaries {
        let list = Command::new(exe)
            .args(["--list", "--format", "terse"])
            .current_dir(root)
            .output()
            .unwrap();
        let tests: Vec<String> = String::from_utf8_lossy(&list.stdout)
            .lines()
            .filter_map(|l| l.strip_suffix(": test"))
            .map(str::to_string)
            .collect();
        for t in &tests {
            reset();
            let _ = Command::new(exe)
                .args(["--exact", t.as_str(), "-q"])
                .current_dir(root)
                .stdout(Stdio::null())
                .stderr(Stdio::null())
                .status();
            for f in &files {
                if fs::metadata(f).unwrap().accessed().unwrap() > stamp + std::time::Duration::from_secs(60) {
                    readers
                        .get_mut(&f.strip_prefix(root).unwrap().display().to_string())
                        .unwrap()
                        .push(format!("{name}::{t}"));
                }
            }
        }
        println!("  {name}: {} tests", tests.len());
    }
    let path = root.join("target/audit/readers.json");
    fs::create_dir_all(path.parent().unwrap()).unwrap();
    fs::write(&path, serde_json::to_string_pretty(&readers).unwrap()).unwrap();
    println!("readers -> {}", path.display());
}
