//! Repository automation: reference XFOIL build and fixture pipeline.
//!
//!   cargo xtask xfoil-build [--verify] [--snan]
//!   cargo xtask fixtures [--case NAME]... [--verify] [--big]
//!   cargo xtask coverage [--case NAME]... [--big] [--rebuild]   (docs/validation/coverage.md)
//!
//! The fixture pipeline enforces CLAUDE.md Rule 4 mechanically: geometry is generated by
//! YFoil, written at 17 significant digits, LOADed into instrumented XFOIL, and the panels
//! XFOIL dumps after ABCOPY must equal YFoil's bitwise before a run is accepted.

mod coverage;

use serde::Deserialize;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

#[derive(Debug, Deserialize)]
struct Cases {
    #[serde(rename = "case")]
    cases: Vec<Case>,
}

#[derive(Debug, Deserialize, Clone)]
struct Case {
    name: String,
    airfoil: String,
    n_panels: usize,
    alphas: Vec<f64>,
    #[serde(default)]
    alphas_after_reinit: Vec<f64>,
    /// Drive the sweep with XFOIL's ASEQ (ALFA a0 / ASEQ a1 aN da / INIT / ALFA / ASEQ) instead
    /// of one ALFA per point; ASEQ gives each point ITMAX+5 iterations, as the polar procedure does.
    #[serde(default)]
    polar: bool,
    /// Fixed-CL points (OPER `CL x`), run after the alpha points
    #[serde(default)]
    cls: Vec<f64>,
    /// OPER `TYPE n`: MATYP = RETYP = n (Mach/Re dependence on CL); 0 = leave XFOIL's default (1)
    #[serde(default)]
    matyp: usize,
    /// Keep only the VISCAL-level records (viscal_*.dat) — for coverage cases that gate on the
    /// converged points rather than the per-subroutine dumps
    #[serde(default)]
    minimal: bool,
    /// Forced transition XTR xu xl (VPAR menu); empty = free transition
    #[serde(default)]
    xtr: Vec<f64>,
    /// OPER `DAMP`: modified envelope e^n amplification (IDAMP = 1)
    #[serde(default)]
    damp: bool,
    /// SETBL/UPDATE call numbers whose per-subroutine dumps to keep (default 1, 2, 3); the
    /// replay harness seeds from `mrchdu_input_<k>.dat` and checks `update_output_<k>.dat`
    #[serde(default)]
    dump_calls: Vec<usize>,
    /// Geometry-only case: XFOIL generates the airfoil itself (`airfoil = "xfoil-naca:0012"`,
    /// OPER never entered); the gate is the PANGEN dump against YFoil's XFOIL-model generator
    #[serde(default)]
    geometry_only: bool,
    #[serde(default)]
    re: f64,
    #[serde(default)]
    mach: f64,
    #[serde(default = "default_ncrit")]
    ncrit: f64,
    #[serde(default = "default_iter")]
    iter: usize,
    #[serde(default)]
    track: bool,
}
fn default_ncrit() -> f64 {
    9.0
}
fn default_iter() -> usize {
    20
}

/// Raw instrumented-XFOIL products worth keeping per case. Everything else in the work
/// directory is transient. Stage-specific JSON parsers are added as each plan stage lands.
const RAW_KEEP: &[&str] = &[
    "stdout.txt",
    "xfoil_trace.log",
    "xfoil_panels.dat",
    "xfoil_inviscid.dat",
    "xfoil_dij.dat",
    "mrchdu_input_1.dat",
    "mrchdu_input_2.dat",
    "mrchdu_input_3.dat",
    "mrchdu_output_1.dat",
    "mrchdu_output_2.dat",
    "mrchdu_output_3.dat",
    "xfoil_mrchdu_trace.dat",
    "setbl_output_1.dat",
    "setbl_output_2.dat",
    "setbl_output_3.dat",
    "update_output_1.dat",
    "update_output_2.dat",
    "update_output_3.dat",
    "viscal_iter.dat",
    "viscal_final.dat",
    "viscal_inviscid.dat",
    "viscal_points.dat",
    "viscal_iters_all.dat",
    "noise_floor.json",
    "xfoil_pangen.dat",
    "blsolv_input.dat",
    "blsolv_output.dat",
    "blsolv_trace.dat",
    "blsolv_vz_trace.dat",
    "xfoil_newton_trace.dat",
    "xfoil_pointers.dat",
    "xfoil_uinv.dat",
];
/// Tracked-fixture budget per case (bytes). CLAUDE.md Rule 7.
const TRACK_BUDGET: u64 = 8 * 1024 * 1024;

fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .to_path_buf()
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    match args.first().map(String::as_str) {
        Some("xfoil-build") => xfoil_build(&args[1..]),
        Some("fixtures") => fixtures(&args[1..]),
        Some("coverage") => coverage::run(&args[1..]),
        _ => {
            eprintln!(
                "usage: cargo xtask <xfoil-build [--verify] [--snan] | fixtures [--case NAME] [--verify] [--big] | coverage [--case NAME] [--big] [--rebuild]>"
            );
            std::process::exit(2);
        }
    }
}

fn xfoil_build(flags: &[String]) {
    let st = Command::new(root().join("scripts/xfoil-build.sh"))
        .args(flags)
        .status()
        .expect("run scripts/xfoil-build.sh");
    if !st.success() {
        std::process::exit(st.code().unwrap_or(1));
    }
}

fn fixtures(flags: &[String]) {
    let root = root();
    let verify = flags.iter().any(|f| f == "--verify");
    let big = flags.iter().any(|f| f == "--big");
    let selected: Vec<&str> = flags
        .windows(2)
        .filter(|w| w[0] == "--case")
        .map(|w| w[1].as_str())
        .collect();

    let cases: Cases =
        toml::from_str(&fs::read_to_string(root.join("fixtures/cases.toml")).expect("fixtures/cases.toml"))
            .expect("parse cases.toml");
    let xfoil = root.join("target/xfoil-ref/instrumented/bin/xfoil");
    if !xfoil.exists() {
        xfoil_build(&[]);
    }
    let yfoil = root.join("target/debug/yfoil");
    run(
        Command::new("cargo")
            .args(["build", "-q", "--bin", "yfoil"])
            .current_dir(&root),
        "cargo build yfoil",
    );
    let ref_manifest = fs::read_to_string(root.join("target/xfoil-ref/manifest.txt")).unwrap_or_default();

    let mut failures = 0;
    for case in &cases.cases {
        if !selected.is_empty() && !selected.contains(&case.name.as_str()) {
            continue;
        }
        if !case.track && !big && selected.is_empty() {
            continue;
        }
        println!("== {} ==", case.name);
        let work = root.join("target/fixtures").join(&case.name);
        let _ = fs::remove_dir_all(&work);
        fs::create_dir_all(&work).unwrap();

        if case.geometry_only {
            // XFOIL's own NACA generator and PANGEN: `NACA dddd` (which calls PANGEN with the
            // default NPAN) then `PPAR / N n` to repanel at the case's n_panels
            let (kind, spec) = case.airfoil.split_once(':').expect("airfoil = \"xfoil-naca:0012\"");
            assert_eq!(kind, "xfoil-naca", "geometry_only cases use xfoil-naca:<digits>");
            let script = format!("PLOP\nG F\n\nNACA {spec}\nPPAR\nN {}\n\n\n\nQUIT\n", case.n_panels);
            fs::write(work.join("xfoil.inp"), &script).unwrap();
            let inp = fs::File::open(work.join("xfoil.inp")).unwrap();
            let out = fs::File::create(work.join("stdout.txt")).unwrap();
            let st = Command::new(&xfoil)
                .current_dir(&work)
                .stdin(inp)
                .stdout(out)
                .stderr(Stdio::inherit())
                .status()
                .expect("run xfoil");
            if !st.success() || !work.join("xfoil_pangen.dat").exists() {
                eprintln!("  xfoil geometry run failed: {st}");
                failures += 1;
                continue;
            }
            let manifest = serde_json::json!({
                "case": { "name": case.name, "airfoil": case.airfoil, "n_panels": case.n_panels, "geometry_only": true },
                "xfoil_ref": ref_manifest.lines().collect::<Vec<_>>(),
                "generated_by": "cargo xtask fixtures",
            });
            fs::write(
                work.join("manifest.json"),
                serde_json::to_string_pretty(&manifest).unwrap(),
            )
            .unwrap();
            if case.track {
                let dst = root.join("tests/fixtures/xfoil").join(&case.name);
                let staged: Vec<(PathBuf, Vec<u8>)> = ["manifest.json", "xfoil.inp", "xfoil_pangen.dat"]
                    .iter()
                    .map(|n| (dst.join(n), fs::read(work.join(n)).unwrap()))
                    .collect();
                if verify {
                    let mut diffs = 0;
                    for (p, b) in &staged {
                        if p.file_name().unwrap() == "manifest.json" {
                            continue;
                        }
                        if fs::read(p).ok().as_deref() != Some(b.as_slice()) {
                            eprintln!("  DIFFERS: {}", p.display());
                            diffs += 1;
                        }
                    }
                    if diffs > 0 {
                        failures += 1;
                    } else {
                        println!("  verify: {} tracked files byte-identical", staged.len() - 1);
                    }
                } else {
                    fs::create_dir_all(&dst).unwrap();
                    for (p, b) in &staged {
                        fs::write(p, b).unwrap();
                    }
                    println!("  tracked {} files -> {}", staged.len(), dst.display());
                }
            }
            continue;
        }

        // 1. geometry, by YFoil only
        let mut parts = case.airfoil.split(':');
        let kind = parts.next().unwrap();
        let spec = parts.next().expect("airfoil = \"naca4:0012[:sharp]\"");
        let sharp = matches!(parts.next(), Some("sharp"));
        assert_eq!(kind, "naca4", "only naca4 supported so far");
        let npan = case.n_panels.to_string();
        let mut gargs = vec!["geom", "naca", spec, "-n", &npan, "-o", "panels.json"];
        if sharp {
            gargs.push("--sharp");
        }
        run(Command::new(&yfoil).args(&gargs).current_dir(&work), "yfoil geom naca");
        run(
            Command::new(&yfoil)
                .args([
                    "geom",
                    "convert",
                    "panels.json",
                    "--to",
                    "dat",
                    "--name",
                    &case.name,
                    "-o",
                    "panels.dat",
                ])
                .current_dir(&work),
            "yfoil geom convert",
        );

        // 2. XFOIL script: LOAD (never NACA/PANE/PPAR), pinned defaults, alpha sequence
        let mut s = String::from("PLOP\nG F\n\nLOAD panels.dat\nOPER\n");
        let xtr = if case.xtr.is_empty() {
            String::new()
        } else {
            assert_eq!(case.xtr.len(), 2, "xtr = [xu, xl]");
            format!("XTR {} {}\n", case.xtr[0], case.xtr[1])
        };
        s += &format!(
            "VISC {}\nMACH {}\nVPAR\nN {}\n{xtr}\nITER {}\n",
            case.re, case.mach, case.ncrit, case.iter
        );
        if case.matyp != 0 {
            s += &format!("TYPE {}\n", case.matyp);
        }
        if case.damp {
            s += "DAMP\n";
        }
        let seq = |s: &mut String, alphas: &[f64]| {
            // ALFA for the first point, ASEQ for the rest (uniform step asserted)
            s.push_str(&format!("ALFA {}\n", alphas[0]));
            if alphas.len() > 1 {
                let da = alphas[1] - alphas[0];
                for w in alphas.windows(2) {
                    assert!(
                        ((w[1] - w[0]) - da).abs() < 1e-12,
                        "polar alphas must be uniformly spaced"
                    );
                }
                s.push_str(&format!("ASEQ {} {} {}\n", alphas[1], alphas[alphas.len() - 1], da));
            }
        };
        if case.polar {
            seq(&mut s, &case.alphas);
            if !case.alphas_after_reinit.is_empty() {
                s += "INIT\n";
                seq(&mut s, &case.alphas_after_reinit);
            }
        } else {
            for a in &case.alphas {
                s += &format!("ALFA {a}\nCPWR cp_a{a}.dat\nDUMP bl_a{a}.dat\n");
            }
            if !case.alphas_after_reinit.is_empty() {
                s += "INIT\n";
                for a in &case.alphas_after_reinit {
                    s += &format!("ALFA {a}\nCPWR cp_a{a}.dat\nDUMP bl_a{a}.dat\n");
                }
            }
        }
        for c in &case.cls {
            s += &format!("CL {c}\n");
        }
        s += "\nQUIT\n";
        fs::write(work.join("xfoil.inp"), &s).unwrap();
        if !case.dump_calls.is_empty() {
            let list: Vec<String> = case.dump_calls.iter().map(|k| k.to_string()).collect();
            fs::write(work.join("dump_calls.txt"), list.join("\n") + "\n").unwrap();
        }
        let inp = fs::File::open(work.join("xfoil.inp")).unwrap();
        let out = fs::File::create(work.join("stdout.txt")).unwrap();
        let st = Command::new(&xfoil)
            .current_dir(&work)
            .stdin(inp)
            .stdout(out)
            .stderr(Stdio::inherit())
            .status()
            .expect("run xfoil");
        if !st.success() {
            eprintln!("  xfoil exited {st}");
            failures += 1;
            continue;
        }

        // 3. bitwise geometry handoff (Rule 4)
        match check_handoff(&work) {
            Ok(n) => println!("  handoff: {n} nodes bitwise identical"),
            Err(e) => {
                eprintln!("  HANDOFF FAILED: {e}");
                failures += 1;
                continue;
            }
        }

        // 3b. the +1-ULP twin: the reference's own noise floor for this case (CLAUDE.md Rule 1)
        match ulp_twin(&xfoil, &work) {
            Ok(summary) => println!("  noise floor: {summary}"),
            Err(e) => {
                eprintln!("  NOISE FLOOR FAILED: {e}");
                failures += 1;
                continue;
            }
        }

        // 4. manifest
        let manifest = serde_json::json!({
            "case": { "name": case.name, "airfoil": case.airfoil, "n_panels": case.n_panels, "alphas": case.alphas,
                      "alphas_after_reinit": case.alphas_after_reinit, "re": case.re, "mach": case.mach,
                      "ncrit": case.ncrit, "iter": case.iter, "polar": case.polar, "cls": case.cls, "matyp": case.matyp, "xtr": case.xtr, "damp": case.damp, "dump_calls": case.dump_calls },
            "panels_dat_sha256": sha256(&work.join("panels.dat")),
            "xfoil_ref": ref_manifest.lines().collect::<Vec<_>>(),
            "generated_by": "cargo xtask fixtures",
        });
        fs::write(
            work.join("manifest.json"),
            serde_json::to_string_pretty(&manifest).unwrap(),
        )
        .unwrap();

        // 5. track or verify
        if case.track {
            let dst = root.join("tests/fixtures/xfoil").join(&case.name);
            let mut staged: Vec<(PathBuf, Vec<u8>)> = vec![];
            for name in ["panels.json", "panels.dat", "manifest.json", "xfoil.inp"]
                .iter()
                .chain(RAW_KEEP.iter())
            {
                if case.minimal
                    && !name.starts_with("viscal_")
                    && !name.starts_with("panels")
                    && *name != "manifest.json"
                    && *name != "xfoil.inp"
                    && *name != "noise_floor.json"
                {
                    continue;
                }
                let p = work.join(name);
                if p.exists() {
                    staged.push((dst.join(name), fs::read(&p).unwrap()));
                }
            }
            for entry in fs::read_dir(&work).unwrap().flatten() {
                let n = entry.file_name().to_string_lossy().to_string();
                if !case.minimal && (n.starts_with("cp_a") || n.starts_with("bl_a")) {
                    staged.push((dst.join(&n), fs::read(entry.path()).unwrap()));
                }
                // per-call replay dumps beyond the default 1..3 (already in RAW_KEEP)
                let per_call = ["mrchdu_input_", "mrchdu_output_", "setbl_output_", "update_output_"];
                if !case.dump_calls.is_empty()
                    && per_call.iter().any(|p| n.starts_with(p))
                    && !RAW_KEEP.contains(&n.as_str())
                {
                    staged.push((dst.join(&n), fs::read(entry.path()).unwrap()));
                }
            }
            let total: u64 = staged.iter().map(|(_, b)| b.len() as u64).sum();
            if total > TRACK_BUDGET {
                eprintln!("  tracked size {} exceeds budget {}", total, TRACK_BUDGET);
                failures += 1;
                continue;
            }
            if verify {
                let mut diffs = 0;
                for (p, b) in &staged {
                    // manifest carries host/toolchain lines and may legitimately differ across hosts
                    if p.file_name().unwrap() == "manifest.json" {
                        continue;
                    }
                    if fs::read(p).ok().as_deref() != Some(b.as_slice()) {
                        eprintln!("  DIFFERS: {}", p.display());
                        diffs += 1;
                    }
                }
                if diffs > 0 {
                    failures += 1;
                } else {
                    println!("  verify: {} tracked files byte-identical", staged.len() - 1);
                }
            } else {
                let _ = fs::remove_dir_all(&dst);
                fs::create_dir_all(&dst).unwrap();
                for (p, b) in &staged {
                    fs::write(p, b).unwrap();
                }
                println!(
                    "  tracked {} files ({} bytes) -> {}",
                    staged.len(),
                    total,
                    dst.strip_prefix(&root).unwrap().display()
                );
            }
        } else {
            println!("  kept in {}", work.strip_prefix(&root).unwrap().display());
        }
    }
    if failures > 0 {
        eprintln!("{failures} case(s) failed");
        std::process::exit(1);
    }
}

/// Parse xfoil_panels.dat (ABCOPY dump, ES24.16) and compare bitwise against panels.json.
fn check_handoff(work: &Path) -> Result<usize, String> {
    #[derive(Deserialize)]
    struct Geom {
        x_c: Vec<f64>,
        y_c: Vec<f64>,
    }
    let g: Geom = serde_json::from_str(&fs::read_to_string(work.join("panels.json")).map_err(|e| e.to_string())?)
        .map_err(|e| e.to_string())?;
    let dump = fs::read_to_string(work.join("xfoil_panels.dat"))
        .map_err(|_| "xfoil_panels.dat missing (ABCOPY dump)".to_string())?;
    let mut n = 0;
    for line in dump.lines() {
        let p: Vec<&str> = line.split_whitespace().collect();
        if p.len() != 7 || p[0].parse::<usize>().is_err() {
            continue;
        }
        let i: usize = p[0].parse().unwrap();
        let (x, y): (f64, f64) = (p[1].parse().map_err(|_| "bad x")?, p[2].parse().map_err(|_| "bad y")?);
        if i == 0 || i > g.x_c.len() {
            return Err(format!("node index {i} out of range"));
        }
        if x.to_bits() != g.x_c[i - 1].to_bits() || y.to_bits() != g.y_c[i - 1].to_bits() {
            return Err(format!(
                "node {i}: xfoil=({x:e},{y:e}) yfoil=({:e},{:e})",
                g.x_c[i - 1],
                g.y_c[i - 1]
            ));
        }
        n += 1;
    }
    if n != g.x_c.len() {
        return Err(format!("xfoil dumped {n} nodes, yfoil has {}", g.x_c.len()));
    }
    Ok(n)
}

fn sha256(p: &Path) -> String {
    let out = Command::new("shasum")
        .args(["-a", "256"])
        .arg(p)
        .output()
        .expect("shasum");
    String::from_utf8_lossy(&out.stdout)
        .split_whitespace()
        .next()
        .unwrap_or("")
        .to_string()
}

fn run(cmd: &mut Command, what: &str) {
    let st = cmd.status().unwrap_or_else(|e| panic!("{what}: {e}"));
    if !st.success() {
        eprintln!("{what} failed: {st}");
        std::process::exit(1);
    }
}

/// Run the case again on panels perturbed by +1 ULP in every coordinate and write
/// `noise_floor.json`: per VISCAL call, the absolute spread of the per-point values and of every
/// per-iteration value, plus whether the branch trace (iteration counts, convergence, IST,
/// ITRAN) survived the perturbation.
fn ulp_twin(xfoil: &Path, work: &Path) -> Result<String, String> {
    let ulp = work.join("ulp");
    let _ = fs::remove_dir_all(&ulp);
    fs::create_dir_all(&ulp).map_err(|e| e.to_string())?;
    let src = fs::read_to_string(work.join("panels.dat")).map_err(|e| e.to_string())?;
    let mut lines = src.lines();
    let mut out = String::new();
    out.push_str(lines.next().unwrap_or(""));
    out.push('\n');
    for l in lines {
        let t: Vec<&str> = l.split_whitespace().collect();
        if t.len() < 2 {
            continue;
        }
        let x: f64 = t[0].parse().map_err(|_| format!("bad coordinate {l}"))?;
        let y: f64 = t[1].parse().map_err(|_| format!("bad coordinate {l}"))?;
        out.push_str(&format!(" {:.17e}  {:.17e}\n", next_up(x), next_up(y)));
    }
    fs::write(ulp.join("panels.dat"), out).map_err(|e| e.to_string())?;
    fs::copy(work.join("xfoil.inp"), ulp.join("xfoil.inp")).map_err(|e| e.to_string())?;
    if work.join("dump_calls.txt").exists() {
        fs::copy(work.join("dump_calls.txt"), ulp.join("dump_calls.txt")).map_err(|e| e.to_string())?;
    }
    let inp = fs::File::open(ulp.join("xfoil.inp")).map_err(|e| e.to_string())?;
    let so = fs::File::create(ulp.join("stdout.txt")).map_err(|e| e.to_string())?;
    let st = Command::new(xfoil)
        .current_dir(&ulp)
        .stdin(inp)
        .stdout(so)
        .stderr(Stdio::inherit())
        .status()
        .map_err(|e| e.to_string())?;
    if !st.success() {
        return Err(format!("xfoil (ulp twin) exited {st}"));
    }

    let pa = parse_points(&work.join("viscal_points.dat"))?;
    let pb = parse_points(&ulp.join("viscal_points.dat"))?;
    let ia = parse_iters(&work.join("viscal_iters_all.dat"))?;
    let ib = parse_iters(&ulp.join("viscal_iters_all.dat"))?;

    // call 1's viscal_iter.dat carries UPDATE's RMXBL and the reported limiter VMXBL/IMXBL/ISMXBL
    let qa = parse_blocks(&work.join("viscal_iter.dat"), "ITER").unwrap_or_default();
    let qb = parse_blocks(&ulp.join("viscal_iter.dat"), "ITER").unwrap_or_default();

    let mut flips: Vec<String> = Vec::new();
    if pa.len() != pb.len() {
        flips.push(format!("VISCAL call count {} vs {}", pa.len(), pb.len()));
    }
    let point_keys = [
        "ALFA", "CL", "CM", "CD", "CDF", "CDP", "XOCTR1", "XOCTR2", "MINF", "REINF", "RMSBL",
    ];
    let iter_keys = ["RMSBL", "RLX", "CL", "CD", "CM", "ALFA", "MINF", "REINF"];
    let iter_cols = [1usize, 2, 3, 4, 5, 10, 11, 12];
    let mut calls = Vec::new();
    for (k, (a, b)) in pa.iter().zip(&pb).enumerate() {
        let call = k + 1;
        for key in ["NITDONE", "LVCONV", "IST", "ITRAN1", "ITRAN2"] {
            if a.get(key) != b.get(key) {
                flips.push(format!(
                    "call {call}: {key} {} vs {}",
                    a.get(key).cloned().unwrap_or_default(),
                    b.get(key).cloned().unwrap_or_default()
                ));
            }
        }
        let mut point = serde_json::Map::new();
        for key in point_keys {
            if let (Some(x), Some(y)) = (a.get(key), b.get(key)) {
                let (x, y): (f64, f64) = (x.parse().unwrap_or(0.0), y.parse().unwrap_or(0.0));
                point.insert(key.to_string(), serde_json::json!((x - y).abs()));
            }
        }
        let (ra, rb) = (
            ia.get(&call).cloned().unwrap_or_default(),
            ib.get(&call).cloned().unwrap_or_default(),
        );
        if ra.len() != rb.len() {
            flips.push(format!("call {call}: iteration count {} vs {}", ra.len(), rb.len()));
        }
        let mut iterations = Vec::new();
        for (i, (x, y)) in ra.iter().zip(&rb).enumerate() {
            for (name, col) in [("IST", 7usize), ("ITRAN1", 8), ("ITRAN2", 9)] {
                if x[col] != y[col] {
                    flips.push(format!(
                        "call {call} iteration {}: {name} {} vs {}",
                        i + 1,
                        x[col],
                        y[col]
                    ));
                }
            }
            let mut m = serde_json::Map::new();
            for (key, col) in iter_keys.iter().zip(iter_cols) {
                m.insert(key.to_string(), serde_json::json!((x[col] - y[col]).abs()));
            }
            if call == 1 {
                if let (Some(ba), Some(bb)) = (qa.get(i), qb.get(i)) {
                    let (ra, rb): (f64, f64) = (
                        ba.get("RMXBL").and_then(|v| v.parse().ok()).unwrap_or(0.0),
                        bb.get("RMXBL").and_then(|v| v.parse().ok()).unwrap_or(0.0),
                    );
                    m.insert("RMXBL".to_string(), serde_json::json!((ra - rb).abs()));
                    let same = ba.get("VMXBL") == bb.get("VMXBL")
                        && ba.get("IMXBL") == bb.get("IMXBL")
                        && ba.get("ISMXBL") == bb.get("ISMXBL");
                    m.insert(
                        "LIMITER_FLIP".to_string(),
                        serde_json::json!(if same { 0.0 } else { 1.0 }),
                    );
                }
            }
            iterations.push(serde_json::Value::Object(m));
        }
        calls.push(serde_json::json!({ "call": call, "point": point, "iterations": iterations }));
    }
    // per-station spreads of the dumped post-UPDATE arrays (replay harness): max |base - twin|
    // over stations, per array, keyed by call number
    let mut arrays = serde_json::Map::new();
    for entry in fs::read_dir(work).map_err(|e| e.to_string())?.flatten() {
        let n = entry.file_name().to_string_lossy().to_string();
        let Some(k) = n.strip_prefix("update_output_").and_then(|r| r.strip_suffix(".dat")) else {
            continue;
        };
        let twin = ulp.join(&n);
        if !twin.exists() {
            continue;
        }
        let names = ["XSSI", "UEDG", "THET", "DSTR", "CTAU", "MASS"];
        let mut worst = [0.0_f64; 6];
        let rows = |p: &Path| -> Vec<Vec<f64>> {
            fs::read_to_string(p)
                .unwrap_or_default()
                .lines()
                .filter(|l| l.starts_with("BL("))
                .map(|l| {
                    l.split_once(")=")
                        .unwrap()
                        .1
                        .split_whitespace()
                        .map(|t| t.parse().unwrap_or(f64::NAN))
                        .collect()
                })
                .collect()
        };
        for (a, b) in rows(&entry.path()).iter().zip(rows(&twin)) {
            for m in 0..6 {
                worst[m] = worst[m].max((a[m] - b[m]).abs());
            }
        }
        let mut per = serde_json::Map::new();
        for (m, name) in names.iter().enumerate() {
            per.insert(name.to_string(), serde_json::json!(worst[m]));
        }
        arrays.insert(k.to_string(), serde_json::Value::Object(per));
    }
    let branch_identical = flips.is_empty();
    let j = serde_json::json!({
        "method": "every panel coordinate +1 ULP; same OPER script; absolute |base - twin| per value",
        "branch_identical": branch_identical,
        "flips": flips,
        "calls": calls,
        "update_output": arrays,
    });
    fs::write(work.join("noise_floor.json"), serde_json::to_string_pretty(&j).unwrap()).map_err(|e| e.to_string())?;
    let worst_point = calls
        .iter()
        .flat_map(|c| c["point"].as_object().unwrap().values().map(|v| v.as_f64().unwrap()))
        .fold(0.0_f64, f64::max);
    let worst_iter = calls
        .iter()
        .flat_map(|c| c["iterations"].as_array().unwrap().iter())
        .flat_map(|m| {
            m.as_object()
                .unwrap()
                .iter()
                .filter(|(k, _)| k.as_str() != "LIMITER_FLIP")
                .map(|(_, v)| v.as_f64().unwrap())
        })
        .fold(0.0_f64, f64::max);
    Ok(if branch_identical {
        format!(
            "branch trace identical; worst point spread {worst_point:.2e}, worst per-iteration spread {worst_iter:.2e}"
        )
    } else {
        format!("THRESHOLD-STRADDLING ({} flips: {})", flips.len(), flips.join("; "))
    })
}

/// The next representable f64 towards +∞ (f64::next_up needs Rust 1.86).
fn next_up(x: f64) -> f64 {
    if x.is_nan() || x == f64::INFINITY {
        return x;
    }
    if x == 0.0 {
        return f64::from_bits(1);
    }
    let bits = x.to_bits();
    if x > 0.0 {
        f64::from_bits(bits + 1)
    } else {
        f64::from_bits(bits - 1)
    }
}

fn parse_blocks(p: &Path, start_key: &str) -> Result<Vec<std::collections::HashMap<String, String>>, String> {
    let text = fs::read_to_string(p).map_err(|e| format!("{}: {e}", p.display()))?;
    let mut out: Vec<std::collections::HashMap<String, String>> = Vec::new();
    for l in text.lines() {
        let Some((k, v)) = l.split_once('=') else { continue };
        if k.trim() == start_key {
            out.push(Default::default());
        }
        if let Some(cur) = out.last_mut() {
            cur.insert(k.trim().to_string(), v.trim().to_string());
        }
    }
    Ok(out)
}

fn parse_points(p: &Path) -> Result<Vec<std::collections::HashMap<String, String>>, String> {
    let text = fs::read_to_string(p).map_err(|e| format!("{}: {e}", p.display()))?;
    let mut out: Vec<std::collections::HashMap<String, String>> = Vec::new();
    for l in text.lines() {
        let Some((k, v)) = l.split_once('=') else { continue };
        if k.trim() == "CALL" {
            out.push(Default::default());
        }
        if let Some(cur) = out.last_mut() {
            cur.insert(k.trim().to_string(), v.trim().to_string());
        }
    }
    Ok(out)
}

fn parse_iters(p: &Path) -> Result<std::collections::HashMap<usize, Vec<Vec<f64>>>, String> {
    let text = fs::read_to_string(p).map_err(|e| format!("{}: {e}", p.display()))?;
    let mut out: std::collections::HashMap<usize, Vec<Vec<f64>>> = Default::default();
    for l in text.lines() {
        let Some(r) = l.strip_prefix("IT ") else { continue };
        let v: Vec<f64> = r.split_whitespace().map(|t| t.parse().unwrap_or(f64::NAN)).collect();
        out.entry(v[0] as usize).or_default().push(v[1..].to_vec());
    }
    Ok(out)
}
